TypeConfig Class Reference
#include <TypeConfig.h>
Public Member Functions
TypeConfig (const AnsiString aName)
TypeConfig (const TypeConfig &kopia)
TypeConfig (TStream &stream)
~TypeConfig ()
bool saveToStream (TStream &aWhere)
bool loadFromStream (TStream &aFrom)
const AnsiString & getName ()
unsigned long getId ()
Protected Attributes
AnsiString nazwa
unsigned long id
Detailed Description
TypeConfig - Klasa reprezentujaca typ przesylany do bloku zdefiniowany przez uzytkownika.
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 16 of file TypeConfig.h.
Constructor & Destructor Documentation
TypeConfig::TypeConfig (const AnsiString aName)
Konstruktor
Parameters:
aName - nazwa nowego typu.
Definition at line 8 of file TypeConfig.cpp.
References nazwa.
TypeConfig::TypeConfig (const TypeConfig & kopia)
Konstruktor kopiujacy.
Parameters:
kopia obiekt ktory zostanie skopiowany
Definition at line 22 of file TypeConfig.cpp.
References id, and nazwa.
TypeConfig::TypeConfig (TStream & stream)
Konstruktor
Parameters:
stream - strumien z ktorego zostana odczytane dane.
Definition at line 16 of file TypeConfig.cpp.
References loadFromStream().
TypeConfig::~TypeConfig ()
Destruktor
Definition at line 28 of file TypeConfig.cpp.
Member Function Documentation
bool TypeConfig::saveToStream (TStream & aWhere)
Zapisuje listê obiektow do strumienia.
Parameters:
aWhere strumien w ktorym zostana zapisane informacje.
Returns: true - jezeli operacja sie powiodla false - jezeli nie.
Reimplemented from BlockConfig.
Definition at line 33 of file TypeConfig.cpp.
References id, nazwa, and BlockConfig::saveToStream2().
bool TypeConfig::loadFromStream (TStream & aFrom)
Odczytuje infomracjê o obiektach na liscie z strumienia
Parameters:
aName nazwa obiektu
Returns: true - jezeli operacja sie powiodla false - jezeli nie.
Reimplemented from BlockConfig.
Definition at line 48 of file TypeConfig.cpp.
References BlockConfig::clear(), BlockConfig::loadFromStream2(), and nazwa.
Referenced by TypeConfig().
const AnsiString & TypeConfig::getName ()
Pobiera nazwe.
Returns: nazwa obiektu.
Definition at line 66 of file TypeConfig.cpp.
References nazwa.
Referenced by PIWOEngine::runBlock().
unsigned long TypeConfig::getId ()
Zwraca unikalny id dla tej klasy, jest nim adres w pamieci pod ktorym zostala stworzona
Definition at line 71 of file TypeConfig.cpp.
References id.
Member Data Documentation
AnsiString TypeConfig::nazwa [protected]
Definition at line 19 of file TypeConfig.h.
Referenced by getName(), loadFromStream(), saveToStream(), and TypeConfig().
unsigned long TypeConfig::id [protected]
Definition at line 20 of file TypeConfig.h.
Referenced by getId(), saveToStream(), and TypeConfig().
The documentation for this class was generated from the following files:
/PIWO/Program/engine/TypeConfig.h
/PIWO/Program/engine/TypeConfig.cpp