Item Class Reference
#include <Item.h>
Public Member Functions
Item (const AnsiString aName, void *aObject, const AnsiString aType)
Item (const Item &copy)
AnsiString & getName ()
void * getObject ()
bool setObject (void *aObject)
AnsiString & getType ()
Private Attributes
AnsiString name
void * pointer
AnsiString type
Detailed Description
Item - Klasa pojemnik przechowujaca elementy dla listy BlockConfig/TypeConfig UWAGA: Klasa nie zwalnia danych przesylanych jako wskaznik do konstruktora (aObiekt), osoba uzywajaca klasy sama musi to oprogramowac.
Author: Piotr Zegar
Date: 2008.11.25
Version: 0.1
Definition at line 16 of file Item.h.
Constructor & Destructor Documentation
Item::Item (const AnsiString aName, void * aObject, const AnsiString aType)
Konstruktor. Inicjuje pola prywatne nie pozwalajac na ich zmianne, konstruktor wywala wyjatek gdy parametry sa bledne
Parameters:
aName Nazwa pod jaka bed¹ przechowywane te dane, niemoze byc pusta
aObiekt Obiekt ktory ma zostac powiazany z nazw¹, niemoze byæ NULL
aType informacja o typie obiektu, nie uzywana wewnatrz klasy, nie mo¿e byc puste
See also: Item(Item &kopia)
Definition at line 29 of file Item.cpp.
References name, pointer, and type.
Item::Item (const Item & copy)
Konstruktor kopiujacy Kopiuje obiekt, wymagany dla vector
Parameters:
kopia obiekt kopiowany
See also: Item(string aName, void* aObject, string aType)
Definition at line 39 of file Item.cpp.
References name, pointer, and type.
Member Function Documentation
AnsiString & Item::getName ()
Pobiera i zwraca nazwe podawana w konstruktorze, zwracana wartosc nie jest pustym stringiem
Returns: name
Definition at line 3 of file Item.cpp.
References name.
void * Item::getObject ()
Pobiera i zwraca wskaznik do danych jakie przechowuje obiekt, zwracana wartosc nie jest nullem
Returns: wsk
Definition at line 8 of file Item.cpp.
References pointer.
Referenced by BlockConfig::getBitmap(), BlockConfig::getBoolean(), BlockConfig::getDouble(), BlockConfig::getInt(), BlockConfig::getStream(), BlockConfig::getString(), BlockConfig::remove(), BlockConfig::setBitmap(), BlockConfig::setBoolean(), BlockConfig::setDouble(), BlockConfig::setInt(), BlockConfig::setStream(), and BlockConfig::setString().
bool Item::setObject (void * aObject)
Ustawia nowy obiekt
Parameters:
aObiekt obiekt ktory zostanie dodany do listy.
Returns: true/false w zaleznosci czy obiekt zostal pomyslnei zainicjalizowany
Definition at line 13 of file Item.cpp.
References pointer.
Referenced by BlockConfig::setBitmap(), BlockConfig::setBoolean(), BlockConfig::setDouble(), BlockConfig::setInt(), BlockConfig::setStream(), and BlockConfig::setString().
AnsiString & Item::getType ()
Pobiera i zwraca nazwe typu danych jaka user powi¹zal z danymi i t¹ nazw¹, nigdy nie zwraca pustego stringu
Returns: type
Definition at line 24 of file Item.cpp.
References type.
Referenced by BlockConfig::getBitmap(), BlockConfig::getBoolean(), BlockConfig::getDouble(), BlockConfig::getInt(), BlockConfig::getStream(), BlockConfig::getString(), BlockConfig::getType(), BlockConfig::isBitmap(), BlockConfig::isBoolean(), BlockConfig::isDouble(), BlockConfig::isInt(), BlockConfig::isStream(), BlockConfig::isString(), BlockConfig::remove(), BlockConfig::setBitmap(), BlockConfig::setBoolean(), BlockConfig::setDouble(), BlockConfig::setInt(), BlockConfig::setStream(), and BlockConfig::setString().
Member Data Documentation
AnsiString Item::name [private]
Definition at line 19 of file Item.h.
Referenced by getName(), and Item().
void* Item::pointer [private]
Definition at line 20 of file Item.h.
Referenced by getObject(), Item(), and setObject().
AnsiString Item::type [private]
Definition at line 21 of file Item.h.
Referenced by getType(), and Item().
The documentation for this class was generated from the following files:
/PIWO/Program/engine/Item.h
/PIWO/Program/engine/Item.cpp