PIWOEngine Class Reference
#include <PIWOEngine.h>
Public Member Functions
__fastcall PIWOEngine (TComponent *Owner)
__fastcall ~PIWOEngine ()
bool AddBlock (const AnsiString &name)
bool DeleteBlock (const AnsiString &fullName)
bool DeleteSelectedBlocks ()
bool DeleteAllBlocks ()
void SelectAllBlocks ()
void InvertBlockSelection ()
void UnselectAllBlocks ()
bool DeleteSelectedConnection ()
bool DeleteAllConnections ()
void UnselectSelectedConnection ()
void CancelCustomizationOnSelectedConnections ()
void CancelCustomizationOnAllConnections ()
void DuplcateSelectedBlocks ()
void validateAll ()
bool run (bool useHistory=true)
bool isRuned ()
void abort (bool wait=false)
bool isAborted ()
bool saveToFile (const AnsiString &filename)
bool loadFromFile (const AnsiString &filename)
bool isChanged ()
int getBlockCount ()
int getConnectionsCount ()
bool isBlockSelected ()
bool isConnectionSelected ()
Public Attributes
Graphics::TBitmap * defaultBlockImage
PIWOEngine_Log OnInformation
PIWOEngine_Log OnDebug
PIWOEngine_Log OnSuccess
PIWOEngine_Log OnWarrning
PIWOEngine_Log OnError
PIWOEngine_Log OnRunInformation
PIWOEngine_Log OnRunDebug
PIWOEngine_Log OnRunSuccess
PIWOEngine_Log OnRunWarrning
PIWOEngine_Log OnRunError
PIWOEngine_Event OnBlockSelected
PIWOEngine_Event OnConnectionSelected
PIWOEngine_Event OnNothingSelected
PIWOEngine_Event OnChanged
PIWOEngine_RunProgress OnRunProgress
PIWOEngine_Event OnRunStart
PIWOEngine_Event OnRunEnd
PluginContener * plugins
vector< THistory * > historyWindows
bool alwaysRun
Private Member Functions
void OnVisualBlockConfigClick (TObject *Sender)
void OnVisualBlockInputSelected (VisualInput *input, TObject *Sender)
void OnVisualBlockOutputSelected (VisualOutput *output, TObject *Sender)
void OnVisualBlockInputHistoryClick (VisualInput *input, TObject *Sender)
void OnVisualBlockOutputHistoryClick (VisualOutput *output, TObject *Sender)
void OnVisualBlockMove (TObject *Sender, bool moveAll, int x, int y)
void OnVisualBlockUnselect (TObject *Sender)
void OnVisualBlockSelect (TObject *Sender)
void OnVisualBlockSelectAdd (TObject *Sender)
void __fastcall onThisClick (TObject *Sender)
void OnConnectionSelect (void *Sender)
void __fastcall HistoryFormClose (TObject *Sender, TCloseAction &Action)
void validateBlock (VisualBlock *block, bool updateInputConnections=true)
Connection * getConnectionTo (VisualInput *input)
bool MakeConnection (VisualBlock *outputBlock, VisualOutput *output, VisualBlock *inputBlock, VisualInput *input)
bool runBlock (VisualBlock *block, bool fastRun, bool *useHistory)
bool runUsingHistory ()
bool runNotUsingHistory ()
Private Attributes
PIWOMAINCLASSTYPE * area
vector< VisualBlock * > blocks
vector< Connection * > connections
Connection * selectedConnection
vector< VisualBlock * > selectedBlocks
VisualBlock * selectedOutputBlock
VisualBlock * selectedInputBlock
VisualInput * selectedInput
VisualOutput * selectedOutput
bool isRunning
bool stopRunning
unsigned int runProgress
bool changed
Detailed Description
Glowna klasa projektu, kazda jej instancja symbolizuje osobny projekt
Definition at line 21 of file PIWOEngine.h.
Constructor & Destructor Documentation
__fastcall PIWOEngine::PIWOEngine (TComponent * Owner)
Konstruktor
Parameters:
Owner komponent bedacy parentem i wlascicielem dla projektu
Definition at line 8 of file PIWOEngine.cpp.
References alwaysRun, area, changed, defaultBlockImage, isRunning, OnBlockSelected, OnConnectionSelected, OnDebug, OnError, OnInformation, OnNothingSelected, OnRunDebug, OnRunEnd, OnRunError, OnRunInformation, OnRunProgress, OnRunStart, OnRunSuccess, OnRunWarrning, OnSuccess, onThisClick(), OnWarrning, PIWOMAINCLASSTYPE, plugins, runProgress, selectedConnection, selectedInput, selectedInputBlock, selectedOutput, selectedOutputBlock, and stopRunning.
__fastcall PIWOEngine::~PIWOEngine ()
Destruktor
Definition at line 61 of file PIWOEngine.cpp.
References area, blocks, connections, and historyWindows.
Member Function Documentation
void PIWOEngine::OnVisualBlockConfigClick (TObject * Sender) [private]
Definition at line 397 of file PIWOEngine.cpp.
References abort(), alwaysRun, VisualBlock::block, changed, Block::getConfig(), PluginContener::getFunction(), BlockConfig::getRevision(), VisualBlock::getTitle(), VisualBlock::nameOfBlock, OnChanged, OnDebug, OnError, OnWarrning, plugins, run(), FunctionDLL::showConfig(), and validateBlock().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockInputSelected (VisualInput * input, TObject * Sender) [private]
Definition at line 529 of file PIWOEngine.cpp.
References abort(), alwaysRun, changed, connections, BlockInput::disconnect(), getConnectionTo(), BlockElement::getDescription(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, MakeConnection(), OnChanged, Connection::outBlock, VisualOutput::output, Connection::output, run(), selectedInput, selectedInputBlock, selectedOutput, selectedOutputBlock, and validateBlock().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockOutputSelected (VisualOutput * output, TObject * Sender) [private]
Definition at line 598 of file PIWOEngine.cpp.
References abort(), alwaysRun, changed, connections, BlockInput::disconnect(), getConnectionTo(), BlockElement::getDescription(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, MakeConnection(), OnChanged, Connection::outBlock, VisualOutput::output, Connection::output, run(), selectedInput, selectedInputBlock, selectedOutput, selectedOutputBlock, and validateBlock().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockInputHistoryClick (VisualInput * input, TObject * Sender) [private]
Definition at line 679 of file PIWOEngine.cpp.
References THistory::block, BlockElement::getDescription(), BlockElement::getName(), VisualBlock::getTitle(), VisualBlock::history, HistoryFormClose(), historyWindows, VisualInput::input, OnDebug, OnWarrning, plugins, THistory::plugins, and THistory::refresh().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockOutputHistoryClick (VisualOutput * output, TObject * Sender) [private]
Definition at line 713 of file PIWOEngine.cpp.
References THistory::block, BlockElement::getDescription(), BlockElement::getName(), VisualBlock::getTitle(), VisualBlock::history, HistoryFormClose(), historyWindows, OnDebug, OnWarrning, VisualOutput::output, plugins, THistory::plugins, and THistory::refresh().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockMove (TObject * Sender, bool moveAll, int x, int y) [private]
Definition at line 747 of file PIWOEngine.cpp.
References changed, connections, OnChanged, and selectedBlocks.
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockUnselect (TObject * Sender) [private]
Definition at line 793 of file PIWOEngine.cpp.
References VisualBlock::getTitle(), OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, selectedBlocks, selectedConnection, and VisualBlock::setSelected().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockSelect (TObject * Sender) [private]
Definition at line 815 of file PIWOEngine.cpp.
References connections, OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, selectedBlocks, selectedConnection, and UnselectSelectedConnection().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void PIWOEngine::OnVisualBlockSelectAdd (TObject * Sender) [private]
Definition at line 844 of file PIWOEngine.cpp.
References connections, OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, selectedBlocks, selectedConnection, and UnselectSelectedConnection().
Referenced by AddBlock(), DuplcateSelectedBlocks(), and loadFromFile().
void __fastcall PIWOEngine::onThisClick (TObject * Sender) [private]
Definition at line 869 of file PIWOEngine.cpp.
References UnselectAllBlocks(), and UnselectSelectedConnection().
Referenced by PIWOEngine().
void PIWOEngine::OnConnectionSelect (void * Sender) [private]
Definition at line 875 of file PIWOEngine.cpp.
References Connection::BringToFront(), BlockElement::getDescription(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, Connection::outBlock, Connection::output, selectedBlocks, selectedConnection, Connection::setSelected(), and UnselectAllBlocks().
Referenced by DuplcateSelectedBlocks(), loadFromFile(), and MakeConnection().
void __fastcall PIWOEngine::HistoryFormClose (TObject * Sender, TCloseAction & Action) [private]
Definition at line 665 of file PIWOEngine.cpp.
References historyWindows, and OnDebug.
Referenced by OnVisualBlockInputHistoryClick(), and OnVisualBlockOutputHistoryClick().
void PIWOEngine::validateBlock (VisualBlock * block, bool updateInputConnections = true) [private]
Definition at line 146 of file PIWOEngine.cpp.
References VisualBlock::block, changed, BlockValidateInputElement::connection, BlockValidateOutputElement::connections, connections, BlockValidateOutputElement::errorCode, BlockValidateInputElement::errorCode, BlockValidateOutputElement::errorDescription, BlockValidateInputElement::errorDescription, BlockElement::getErrorCode(), BlockElement::getErrorDescription(), PluginContener::getFunction(), BlockOutput::getOutputType(), VisualBlock::getTitle(), BlockValidateInputElement::input, Block::input, VisualBlock::nameOfBlock, OnChanged, OnDebug, OnError, BlockValidateOutputElement::output, Block::output, plugins, BlockValidateOutputElement::type, VisualBlock::updateHistory(), and VisualBlock::updateVisualComponents().
Referenced by AddBlock(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), loadFromFile(), MakeConnection(), OnVisualBlockConfigClick(), OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), and validateAll().
Connection * PIWOEngine::getConnectionTo (VisualInput * input) [private]
Definition at line 895 of file PIWOEngine.cpp.
References connections, and VisualInput::input.
Referenced by OnVisualBlockInputSelected(), and OnVisualBlockOutputSelected().
bool PIWOEngine::MakeConnection (VisualBlock * outputBlock, VisualOutput * output, VisualBlock * inputBlock, VisualInput * input) [private]
Definition at line 439 of file PIWOEngine.cpp.
References BlockInput::allowedTypes, area, changed, BlockInput::connect(), connections, Connection::draw(), BlockElement::getDescription(), BlockOutput::getOutputType(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, VisualInput::input, OnBlockSelected, OnChanged, OnConnectionSelect(), OnConnectionSelected, Connection::OnConnectionSelected, OnDebug, OnError, OnInformation, OnNothingSelected, Connection::outBlock, Connection::output, VisualOutput::output, selectedBlocks, selectedConnection, Connection::setSelected(), Connection::update(), and validateBlock().
Referenced by OnVisualBlockInputSelected(), and OnVisualBlockOutputSelected().
bool PIWOEngine::runBlock (VisualBlock * block, bool fastRun, bool * useHistory) [private]
Definition at line 1500 of file PIWOEngine.cpp.
References VisualBlock::block, blocks, BlockHistory::bottomOutput, VisualBlock::bottomOutput, BlockHistory::configRevision, connections, Block::getConfig(), PluginContener::getFunction(), TypeConfig::getName(), BlockElement::getObject(), BlockConfig::getRevision(), VisualBlock::getTitle(), PluginContener::getType(), TypeDLL::getType(), VisualBlock::history, historyWindows, BlockHistoryInputElement::input, Block::input, TypeDLL::isValid(), BlockHistory::leftInput, VisualBlock::leftInput, VisualBlock::nameOfBlock, OnError, OnRunDebug, OnRunError, OnRunInformation, OnRunProgress, OnRunSuccess, OnRunWarrning, Connection::outBlock, BlockHistoryOutputElement::output, Block::output, Connection::output, plugins, BlockHistory::rightOutput, VisualBlock::rightOutput, FunctionDLL::run(), VisualBlock::runned, runProgress, BlockHistoryOutputElement::setData(), BlockHistoryInputElement::setData(), BlockHistoryOutputElement::setNULL(), BlockHistoryInputElement::setNULL(), VisualBlock::setStatusColor(), stopRunning, BlockHistory::topInput, VisualBlock::topInput, Connection::update(), and VisualBlock::updateVisualComponents().
Referenced by runNotUsingHistory(), and runUsingHistory().
bool PIWOEngine::runUsingHistory () [private]
Definition at line 1322 of file PIWOEngine.cpp.
References blocks, connections, isRunning, OnError, OnInformation, OnRunEnd, OnRunError, OnRunInformation, OnRunProgress, OnRunStart, OnRunSuccess, OnRunWarrning, OnSuccess, OnWarrning, runBlock(), runProgress, and stopRunning.
Referenced by run().
bool PIWOEngine::runNotUsingHistory () [private]
Definition at line 1411 of file PIWOEngine.cpp.
References blocks, connections, isRunning, OnError, OnInformation, OnRunEnd, OnRunError, OnRunInformation, OnRunProgress, OnRunStart, OnRunSuccess, OnRunWarrning, OnSuccess, OnWarrning, runBlock(), runProgress, and stopRunning.
Referenced by run().
bool PIWOEngine::AddBlock (const AnsiString & name)
Dodaje blok do projektu
Parameters:
name nazwa bloku
Returns: true jesli blok zostal dodany
Definition at line 84 of file PIWOEngine.cpp.
References abort(), alwaysRun, area, VisualBlock::block, blocks, changed, defaultBlockImage, FunctionDLL::description, FunctionDLL::fullName, PluginContener::getFunction(), VisualBlock::nameOfBlock, VisualBlock::numberOfBlock, VisualBlock::OnBlockMove, OnBlockSelected, OnChanged, VisualBlock::OnConfigClick, OnConnectionSelected, OnDebug, OnInformation, OnNothingSelected, VisualBlock::OnSelect, VisualBlock::OnSelectAdd, VisualBlock::OnUnselect, VisualBlock::OnVInputHistory, OnVisualBlockConfigClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockInputSelected(), OnVisualBlockMove(), OnVisualBlockOutputHistoryClick(), OnVisualBlockOutputSelected(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), VisualBlock::OnVisualInputSelected, VisualBlock::OnVisualOutputSelected, VisualBlock::OnVOutputHistory, FunctionDLL::picture, plugins, run(), selectedBlocks, selectedConnection, VisualBlock::setConfigButtonGlyph(), VisualBlock::setSelected(), VisualBlock::setTitle(), VisualBlock::updateVisualComponents(), FunctionDLL::validate(), and validateBlock().
Referenced by TForm1::OnFunctionAddClick().
bool PIWOEngine::DeleteBlock (const AnsiString & fullName)
Usuwa blok z projektu
Parameters:
fullName tytul bloku (napis widniejacy na nim)
Returns: true jesli blok zostal usuniety
Definition at line 902 of file PIWOEngine.cpp.
References abort(), alwaysRun, blocks, changed, connections, historyWindows, OnBlockSelected, OnChanged, OnConnectionSelected, OnDebug, OnError, OnInformation, OnNothingSelected, run(), selectedBlocks, selectedConnection, and validateBlock().
bool PIWOEngine::DeleteSelectedBlocks ()
Usuwa wszystkie zaznaczone bloki
Returns: true jesli usunieto cos
Definition at line 1005 of file PIWOEngine.cpp.
References abort(), alwaysRun, blocks, changed, connections, historyWindows, OnBlockSelected, OnChanged, OnConnectionSelected, OnDebug, OnInformation, OnNothingSelected, run(), selectedBlocks, selectedConnection, and validateBlock().
Referenced by TForm1::FormKeyDown(), TForm1::ToolButton11Click(), TForm1::Usuzaznaczonebloki1Click(), and TForm1::Usuzaznaczonepoczenie1Click().
bool PIWOEngine::DeleteAllBlocks ()
Usuwa wszywstkie bloki
Returns: true jesli usunieto cos
Definition at line 1114 of file PIWOEngine.cpp.
References abort(), blocks, changed, connections, historyWindows, OnBlockSelected, OnChanged, OnConnectionSelected, OnDebug, OnInformation, OnNothingSelected, selectedBlocks, and selectedConnection.
Referenced by TForm1::Usubloki1Click().
void PIWOEngine::SelectAllBlocks ()
Zaznacza wszystkie bloki
Definition at line 1147 of file PIWOEngine.cpp.
References blocks, OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, selectedBlocks, and selectedConnection.
Referenced by TForm1::Zaznaczwszystkiebloki1Click().
void PIWOEngine::InvertBlockSelection ()
Odwraca zaznaczenie wszystkich blokow
Definition at line 1167 of file PIWOEngine.cpp.
References blocks, OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, selectedBlocks, and selectedConnection.
Referenced by TForm1::Odwrzaznaczenieblokw1Click().
void PIWOEngine::UnselectAllBlocks ()
Odznacza wszystkie bloki
Definition at line 1194 of file PIWOEngine.cpp.
References OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, selectedBlocks, and selectedConnection.
Referenced by TForm1::Odznaczwszystkiebloki1Click(), OnConnectionSelect(), and onThisClick().
bool PIWOEngine::DeleteSelectedConnection ()
Usuwa zaznaczone polaczenie
Returns: true jesli jakies polaczenie jest zaznaczone i zostalo usuniete
Definition at line 1212 of file PIWOEngine.cpp.
References abort(), alwaysRun, changed, connections, BlockInput::disconnect(), BlockElement::getDescription(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, OnBlockSelected, OnChanged, OnConnectionSelected, OnDebug, OnInformation, OnNothingSelected, Connection::outBlock, Connection::output, run(), selectedBlocks, selectedConnection, and validateBlock().
Referenced by TForm1::FormKeyDown(), TForm1::ToolButton11Click(), TForm1::Usuzaznaczonebloki1Click(), and TForm1::Usuzaznaczonepoczenie1Click().
bool PIWOEngine::DeleteAllConnections ()
Usuwa wszystkie polaczenia
Returns: true jesli jakies polaczenie zostalo usuniete
Definition at line 1245 of file PIWOEngine.cpp.
References abort(), alwaysRun, changed, connections, OnBlockSelected, OnChanged, OnConnectionSelected, OnDebug, OnInformation, OnNothingSelected, run(), selectedBlocks, selectedConnection, and validateBlock().
Referenced by TForm1::Usuwszystkiepoczenia1Click().
void PIWOEngine::UnselectSelectedConnection ()
Odznacza zaznaczone polaczenie, jesl jest takie
Definition at line 1286 of file PIWOEngine.cpp.
References BlockElement::getDescription(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, OnBlockSelected, OnConnectionSelected, OnDebug, OnNothingSelected, Connection::outBlock, Connection::output, selectedBlocks, selectedConnection, and Connection::setSelected().
Referenced by TForm1::Odznaczzaznaczonepoaczenie1Click(), onThisClick(), OnVisualBlockSelect(), and OnVisualBlockSelectAdd().
void PIWOEngine::CancelCustomizationOnSelectedConnections ()
Anuluje zmiany wprowadzone przez urzytkownika w zaznaczonym polaczeniu
Definition at line 1302 of file PIWOEngine.cpp.
References changed, BlockElement::getDescription(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, OnChanged, OnDebug, Connection::outBlock, Connection::output, selectedConnection, and Connection::setCustomizeFalse().
Referenced by TForm1::Zresetujzaznaczonepoczenie1Click().
void PIWOEngine::CancelCustomizationOnAllConnections ()
Anuluje zmiany wprowadzone przez urzytkownika we wszystkich polaczeniach
Definition at line 1312 of file PIWOEngine.cpp.
References changed, connections, OnChanged, and OnDebug.
Referenced by TForm1::Zresetujwszystkiepoczenia1Click().
void PIWOEngine::DuplcateSelectedBlocks ()
Duplikuje zaznaczone bloki
Definition at line 2074 of file PIWOEngine.cpp.
References abort(), alwaysRun, area, VisualBlock::block, blocks, changed, BlockInput::connect(), connections, defaultBlockImage, FunctionDLL::description, Connection::draw(), FunctionDLL::fullName, PluginContener::getFunction(), BlockOutput::getOutputType(), Connection::inBlock, Connection::input, Block::input, Connection::lines, VisualBlock::nameOfBlock, VisualBlock::numberOfBlock, VisualBlock::OnBlockMove, OnBlockSelected, OnChanged, VisualBlock::OnConfigClick, OnConnectionSelect(), OnConnectionSelected, Connection::OnConnectionSelected, OnDebug, OnInformation, OnNothingSelected, VisualBlock::OnSelect, VisualBlock::OnSelectAdd, VisualBlock::OnUnselect, VisualBlock::OnVInputHistory, OnVisualBlockConfigClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockInputSelected(), OnVisualBlockMove(), OnVisualBlockOutputHistoryClick(), OnVisualBlockOutputSelected(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), VisualBlock::OnVisualInputSelected, VisualBlock::OnVisualOutputSelected, VisualBlock::OnVOutputHistory, Connection::outBlock, Connection::output, Block::output, FunctionDLL::picture, plugins, run(), selectedBlocks, selectedConnection, Block::setConfig(), VisualBlock::setConfigButtonGlyph(), VisualBlock::setTitle(), Connection::update(), VisualBlock::updateVisualComponents(), and validateBlock().
Referenced by TForm1::Duplikujbloki1Click().
void PIWOEngine::validateAll ()
Sprawsza wszystkie bloki
Definition at line 2475 of file PIWOEngine.cpp.
References abort(), alwaysRun, blocks, OnInformation, run(), and validateBlock().
Referenced by TForm1::Sprawdprojekt1Click().
bool PIWOEngine::run (bool useHistory = true)
Uruchamai projekt
Parameters:
useHistory czy ma uzywac historii
Returns: true jesli uruchomiono bez bledow
Definition at line 2041 of file PIWOEngine.cpp.
References runNotUsingHistory(), and runUsingHistory().
Referenced by AddBlock(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), OnVisualBlockConfigClick(), OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), TForm1::Uruchom3Click(), TForm1::Uruchomwszystko1Click(), and validateAll().
bool PIWOEngine::isRuned ()
Sprawdza czy projekt ejst aktualnie uruchamiany
Returns: true jesli ejst aktualnie uruchamiany, w przeciwnym wypadku false
Definition at line 2046 of file PIWOEngine.cpp.
References isRunning.
Referenced by TForm1::blockMenu().
void PIWOEngine::abort (bool wait = false)
Anuluje uruchamianie projektu
Parameters:
wait czy ma czekac az uruchomienie zostanie anulowane
Definition at line 2051 of file PIWOEngine.cpp.
References isRunning, OnRunInformation, and stopRunning.
Referenced by AddBlock(), TForm1::Anuluj1Click(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), loadFromFile(), OnVisualBlockConfigClick(), OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), saveToFile(), TForm1::SpeedButton1Click(), and validateAll().
bool PIWOEngine::isAborted ()
Czy juz anulowano uruchomienie projektu
Returns: true/false
Definition at line 2069 of file PIWOEngine.cpp.
References stopRunning.
bool PIWOEngine::saveToFile (const AnsiString & filename)
Zapisuje projekt do pliku
Parameters:
filename sciezka do pliku
Returns: false jesli nie zapisano
Definition at line 2219 of file PIWOEngine.cpp.
References abort(), blocks, changed, connections, OnDebug, OnError, OnSuccess, putInt(), and putString().
Referenced by TForm1::closeProject(), TForm1::Exportujjakoobraz1Click(), and TForm1::Zapiszjako1Click().
bool PIWOEngine::loadFromFile (const AnsiString & filename)
Wczytuje projekt z pliku
Parameters:
filename
Returns: false jesli nie wczytano
Definition at line 2311 of file PIWOEngine.cpp.
References abort(), BlockInput::allowedTypes, area, VisualBlock::block, blocks, BlockInput::connect(), connections, defaultBlockImage, FunctionDLL::description, Connection::draw(), FunctionDLL::fullName, Block::getConfig(), PluginContener::getFunction(), getInt(), BlockOutput::getOutputType(), getString(), VisualBlock::getTitle(), Connection::inBlock, Connection::input, Block::input, Connection::lines, BlockConfig::loadFromStream(), VisualBlock::nameOfBlock, VisualBlock::numberOfBlock, VisualBlock::OnBlockMove, VisualBlock::OnConfigClick, OnConnectionSelect(), Connection::OnConnectionSelected, OnDebug, OnError, VisualBlock::OnSelect, VisualBlock::OnSelectAdd, OnSuccess, VisualBlock::OnUnselect, VisualBlock::OnVInputHistory, OnVisualBlockConfigClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockInputSelected(), OnVisualBlockMove(), OnVisualBlockOutputHistoryClick(), OnVisualBlockOutputSelected(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), VisualBlock::OnVisualInputSelected, VisualBlock::OnVisualOutputSelected, VisualBlock::OnVOutputHistory, OnWarrning, Connection::outBlock, Connection::output, Block::output, FunctionDLL::picture, plugins, VisualBlock::setConfigButtonGlyph(), BlockElement::setDescription(), BlockElement::setErrorCode(), BlockElement::setErrorDescription(), BlockOutput::setOutputType(), VisualBlock::setTitle(), Connection::update(), VisualBlock::updateVisualComponents(), and validateBlock().
Referenced by TForm1::FormCreate(), and TForm1::openProject().
bool PIWOEngine::isChanged ()
Czy w projekcie wprowadzono zmiany
Returns: true/false = tak/nie
Definition at line 2465 of file PIWOEngine.cpp.
References changed.
Referenced by TForm1::closeProject().
int PIWOEngine::getBlockCount ()
Zwraca ilosc blokow w projekcie
Returns: ilosc blokow
Definition at line 2470 of file PIWOEngine.cpp.
References blocks.
Referenced by TForm1::blockMenu(), and TForm1::closeProject().
int PIWOEngine::getConnectionsCount ()
Zwraca ilosc polaczen w projekcie
Returns: ilosc polaczen
Definition at line 2492 of file PIWOEngine.cpp.
References connections.
Referenced by TForm1::blockMenu().
bool PIWOEngine::isBlockSelected ()
Czy jakiekolwiek blok jest zaznacozny
Returns: true jesli tak, false jesli nie
Definition at line 2487 of file PIWOEngine.cpp.
References selectedBlocks.
Referenced by TForm1::blockMenu().
bool PIWOEngine::isConnectionSelected ()
Czy polaczenie jest zaznaczone
Returns: true jesli tak, false jesli nie
Definition at line 2497 of file PIWOEngine.cpp.
References selectedConnection.
Referenced by TForm1::blockMenu().
Member Data Documentation
PIWOMAINCLASSTYPE* PIWOEngine::area [private]
Definition at line 24 of file PIWOEngine.h.
Referenced by AddBlock(), DuplcateSelectedBlocks(), loadFromFile(), MakeConnection(), PIWOEngine(), and ~PIWOEngine().
vector<VisualBlock*> PIWOEngine::blocks [private]
Definition at line 25 of file PIWOEngine.h.
Referenced by AddBlock(), DeleteAllBlocks(), DeleteBlock(), DeleteSelectedBlocks(), DuplcateSelectedBlocks(), getBlockCount(), InvertBlockSelection(), loadFromFile(), runBlock(), runNotUsingHistory(), runUsingHistory(), saveToFile(), SelectAllBlocks(), validateAll(), and ~PIWOEngine().
vector<Connection*> PIWOEngine::connections [private]
Definition at line 26 of file PIWOEngine.h.
Referenced by CancelCustomizationOnAllConnections(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), getConnectionsCount(), getConnectionTo(), loadFromFile(), MakeConnection(), OnVisualBlockInputSelected(), OnVisualBlockMove(), OnVisualBlockOutputSelected(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), runBlock(), runNotUsingHistory(), runUsingHistory(), saveToFile(), validateBlock(), and ~PIWOEngine().
Connection* PIWOEngine::selectedConnection [private]
Definition at line 27 of file PIWOEngine.h.
Referenced by AddBlock(), CancelCustomizationOnSelectedConnections(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), InvertBlockSelection(), isConnectionSelected(), MakeConnection(), OnConnectionSelect(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), PIWOEngine(), SelectAllBlocks(), UnselectAllBlocks(), and UnselectSelectedConnection().
vector<VisualBlock*> PIWOEngine::selectedBlocks [private]
Definition at line 28 of file PIWOEngine.h.
Referenced by AddBlock(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), InvertBlockSelection(), isBlockSelected(), MakeConnection(), OnConnectionSelect(), OnVisualBlockMove(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), SelectAllBlocks(), UnselectAllBlocks(), and UnselectSelectedConnection().
VisualBlock* PIWOEngine::selectedOutputBlock [private]
Definition at line 29 of file PIWOEngine.h.
Referenced by OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), and PIWOEngine().
VisualBlock* PIWOEngine::selectedInputBlock [private]
Definition at line 30 of file PIWOEngine.h.
Referenced by OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), and PIWOEngine().
VisualInput* PIWOEngine::selectedInput [private]
Definition at line 31 of file PIWOEngine.h.
Referenced by OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), and PIWOEngine().
VisualOutput* PIWOEngine::selectedOutput [private]
Definition at line 32 of file PIWOEngine.h.
Referenced by OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), and PIWOEngine().
bool PIWOEngine::isRunning [private]
Definition at line 55 of file PIWOEngine.h.
Referenced by abort(), isRuned(), PIWOEngine(), runNotUsingHistory(), and runUsingHistory().
bool PIWOEngine::stopRunning [private]
Definition at line 56 of file PIWOEngine.h.
Referenced by abort(), isAborted(), PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
unsigned int PIWOEngine::runProgress [private]
Definition at line 58 of file PIWOEngine.h.
Referenced by PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
bool PIWOEngine::changed [private]
Definition at line 59 of file PIWOEngine.h.
Referenced by AddBlock(), CancelCustomizationOnAllConnections(), CancelCustomizationOnSelectedConnections(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), isChanged(), MakeConnection(), OnVisualBlockConfigClick(), OnVisualBlockInputSelected(), OnVisualBlockMove(), OnVisualBlockOutputSelected(), PIWOEngine(), saveToFile(), and validateBlock().
Graphics::TBitmap* PIWOEngine::defaultBlockImage
Domyslny obrazek widniejacy na przycisku konfiguracyjnym bloczkow gdy niemaja ustawionego swojego
Definition at line 64 of file PIWOEngine.h.
Referenced by AddBlock(), DuplcateSelectedBlocks(), TForm1::FormCreate(), loadFromFile(), TForm1::newProject(), TForm1::openProject(), and PIWOEngine().
PIWOEngine_Log PIWOEngine::OnInformation
Event: Logowanie - Informacja
Definition at line 68 of file PIWOEngine.h.
Referenced by AddBlock(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), TForm1::FormCreate(), MakeConnection(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runNotUsingHistory(), runUsingHistory(), and validateAll().
PIWOEngine_Log PIWOEngine::OnDebug
Event: Logowanie - Debug
Definition at line 72 of file PIWOEngine.h.
Referenced by AddBlock(), CancelCustomizationOnAllConnections(), CancelCustomizationOnSelectedConnections(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), TForm1::FormCreate(), HistoryFormClose(), InvertBlockSelection(), loadFromFile(), MakeConnection(), TForm1::newProject(), OnConnectionSelect(), OnVisualBlockConfigClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockOutputHistoryClick(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), TForm1::openProject(), PIWOEngine(), saveToFile(), SelectAllBlocks(), UnselectAllBlocks(), UnselectSelectedConnection(), and validateBlock().
PIWOEngine_Log PIWOEngine::OnSuccess
Event: Logowanie - Sukces
Definition at line 76 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), loadFromFile(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runNotUsingHistory(), runUsingHistory(), and saveToFile().
PIWOEngine_Log PIWOEngine::OnWarrning
Event: Logowanie - Ostrzezenie
Definition at line 80 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), loadFromFile(), TForm1::newProject(), OnVisualBlockConfigClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockOutputHistoryClick(), TForm1::openProject(), PIWOEngine(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Log PIWOEngine::OnError
Event: Logowanie - Blad
Definition at line 84 of file PIWOEngine.h.
Referenced by DeleteBlock(), TForm1::FormCreate(), loadFromFile(), MakeConnection(), TForm1::newProject(), OnVisualBlockConfigClick(), TForm1::openProject(), PIWOEngine(), runBlock(), runNotUsingHistory(), runUsingHistory(), saveToFile(), and validateBlock().
PIWOEngine_Log PIWOEngine::OnRunInformation
Event: Logowanie - Podczas uruchamiania - Informacja
Definition at line 88 of file PIWOEngine.h.
Referenced by abort(), TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Log PIWOEngine::OnRunDebug
Event: Logowanie - Podczas uruchamiania - Debug
Definition at line 92 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), and runBlock().
PIWOEngine_Log PIWOEngine::OnRunSuccess
Event: Logowanie - Podczas uruchamiania - Sukces
Definition at line 96 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Log PIWOEngine::OnRunWarrning
Event: Logowanie - Podczas uruchamiania - Ostrzerzenie
Definition at line 100 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Log PIWOEngine::OnRunError
Event: Logowanie - Podczas uruchamiania - Blad
Definition at line 104 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Event PIWOEngine::OnBlockSelected
Event: gdy zaznaczono blok
Definition at line 108 of file PIWOEngine.h.
Referenced by AddBlock(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), TForm1::FormCreate(), InvertBlockSelection(), MakeConnection(), TForm1::newProject(), OnConnectionSelect(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), TForm1::openProject(), PIWOEngine(), SelectAllBlocks(), UnselectAllBlocks(), and UnselectSelectedConnection().
PIWOEngine_Event PIWOEngine::OnConnectionSelected
Event: gdy zaznaczono polaczenie
Definition at line 112 of file PIWOEngine.h.
Referenced by AddBlock(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), TForm1::FormCreate(), InvertBlockSelection(), MakeConnection(), TForm1::newProject(), OnConnectionSelect(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), TForm1::openProject(), PIWOEngine(), SelectAllBlocks(), UnselectAllBlocks(), and UnselectSelectedConnection().
PIWOEngine_Event PIWOEngine::OnNothingSelected
Event: gdy nic nie jest zaznaczone
Definition at line 116 of file PIWOEngine.h.
Referenced by AddBlock(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), TForm1::FormCreate(), InvertBlockSelection(), MakeConnection(), TForm1::newProject(), OnConnectionSelect(), OnVisualBlockSelect(), OnVisualBlockSelectAdd(), OnVisualBlockUnselect(), TForm1::openProject(), PIWOEngine(), SelectAllBlocks(), UnselectAllBlocks(), and UnselectSelectedConnection().
PIWOEngine_Event PIWOEngine::OnChanged
Event: gdy projekt zostal zmodyfikowany
Definition at line 120 of file PIWOEngine.h.
Referenced by AddBlock(), CancelCustomizationOnAllConnections(), CancelCustomizationOnSelectedConnections(), DeleteAllBlocks(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), TForm1::FormCreate(), MakeConnection(), TForm1::newProject(), OnVisualBlockConfigClick(), OnVisualBlockInputSelected(), OnVisualBlockMove(), OnVisualBlockOutputSelected(), TForm1::openProject(), and validateBlock().
PIWOEngine_RunProgress PIWOEngine::OnRunProgress
Event: podczas uruchamiania projektu
Definition at line 124 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runBlock(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Event PIWOEngine::OnRunStart
Event: gdy projekt zostaje uruchomiony
Definition at line 128 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runNotUsingHistory(), and runUsingHistory().
PIWOEngine_Event PIWOEngine::OnRunEnd
Event: gdy projekt zostal uruchomiony
Definition at line 132 of file PIWOEngine.h.
Referenced by TForm1::FormCreate(), TForm1::newProject(), TForm1::openProject(), PIWOEngine(), runNotUsingHistory(), and runUsingHistory().
PluginContener* PIWOEngine::plugins
Kontener pluginow
Definition at line 136 of file PIWOEngine.h.
Referenced by AddBlock(), DuplcateSelectedBlocks(), TForm1::FormCreate(), loadFromFile(), TForm1::newProject(), OnVisualBlockConfigClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockOutputHistoryClick(), TForm1::openProject(), PIWOEngine(), runBlock(), and validateBlock().
vector<THistory*> PIWOEngine::historyWindows
Lista okien histori aktualnie otwartych dla tego projektu
Definition at line 140 of file PIWOEngine.h.
Referenced by TForm1::blockMenu(), DeleteAllBlocks(), DeleteBlock(), DeleteSelectedBlocks(), HistoryFormClose(), TForm1::HistoryMenuClick(), OnVisualBlockInputHistoryClick(), OnVisualBlockOutputHistoryClick(), TForm1::Pokawszystkieokna1Click(), runBlock(), TForm1::Widok1Click(), TForm1::Zamknijwszystkieokna1Click(), and ~PIWOEngine().
bool PIWOEngine::alwaysRun
Czy trym Auto-run ma by wczony
Definition at line 144 of file PIWOEngine.h.
Referenced by AddBlock(), TForm1::blockMenu(), DeleteAllConnections(), DeleteBlock(), DeleteSelectedBlocks(), DeleteSelectedConnection(), DuplcateSelectedBlocks(), OnVisualBlockConfigClick(), OnVisualBlockInputSelected(), OnVisualBlockOutputSelected(), PIWOEngine(), TForm1::Uruchom3Click(), and validateAll().
The documentation for this class was generated from the following files:
/PIWO/Program/gui/PIWOEngine.h
/PIWO/Program/gui/PIWOEngine.cpp