TypeDLL Class Reference
#include <TypeDLL.h>
Public Member Functions
TypeDLL (const AnsiString &fileDLL)
~TypeDLL ()
TFrame * show (TWinControl *parent, TypeConfig *aData)
bool isValid (TypeConfig *aData)
AnsiString getType ()
Private Attributes
AnsiString type
HANDLE DLLHandle
TypeDLL_show fshow
TypeDLL_isValid fisValid
TypeDLL_getType fgetType
Detailed Description
Interfejs pozwalajacy na l¹dowanie i uzywanie biblioteki typu
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 21 of file TypeDLL.h.
Constructor & Destructor Documentation
TypeDLL::TypeDLL (const AnsiString & fileDLL)
Konstruktor
Parameters:
file sciezka do pliku
stype
Definition at line 3 of file TypeDLL.cpp.
References DLLHandle, fgetType, fisValid, and fshow.
TypeDLL::~TypeDLL ()
Destruktor
Definition at line 17 of file TypeDLL.cpp.
References DLLHandle.
Member Function Documentation
TFrame * TypeDLL::show (TWinControl * parent, TypeConfig * aData)
Wykonuje funkcje show w zaladowanej DLL typu
Parameters:
parent wskaznik na obiekt wizualny ktory ma zostac uznany za parent - powinno to byc okno
aData dane
Returns: zwraca wskaznik na obiekt TFrame, naszym obowiaskiem jest prawidlowo zwolnic go.
Definition at line 22 of file TypeDLL.cpp.
References fshow.
Referenced by THistory::refresh().
bool TypeDLL::isValid (TypeConfig * aData)
Sprawdza poprawnosc danych.
Parameters:
aData dane.
Returns: poprawnosc wykonanej operacji
Definition at line 26 of file TypeDLL.cpp.
References fisValid.
Referenced by PIWOEngine::runBlock().
AnsiString TypeDLL::getType ()
Pobiera typ.
Returns: typ.
Definition at line 30 of file TypeDLL.cpp.
References fgetType.
Referenced by PluginContener::LoadData(), THistory::refresh(), and PIWOEngine::runBlock().
Member Data Documentation
AnsiString TypeDLL::type [private]
Definition at line 24 of file TypeDLL.h.
HANDLE TypeDLL::DLLHandle [private]
Definition at line 25 of file TypeDLL.h.
Referenced by TypeDLL(), and ~TypeDLL().
TypeDLL_show TypeDLL::fshow [private]
Definition at line 26 of file TypeDLL.h.
Referenced by show(), and TypeDLL().
TypeDLL_isValid TypeDLL::fisValid [private]
Definition at line 27 of file TypeDLL.h.
Referenced by isValid(), and TypeDLL().
TypeDLL_getType TypeDLL::fgetType [private]
Definition at line 28 of file TypeDLL.h.
Referenced by getType(), and TypeDLL().
The documentation for this class was generated from the following files:
/PIWO/Program/brige/TypeDLL.h
/PIWO/Program/brige/TypeDLL.cpp