BlockInput Class Reference
#include <BlockInput.h>
Public Member Functions
BlockInput (const AnsiString aName)
BlockInput (const BlockInput &kopia)
~BlockInput ()
bool connect (const AnsiString aName)
AnsiString & getConnectedType ()
void disconnect ()
Public Attributes
vector< AnsiString > allowedTypes
Private Attributes
AnsiString inputType
Detailed Description
BlockInput - Klasa pojemnik przechowujaca wejscia i wyjscia bloku
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 15 of file BlockInput.h.
Constructor & Destructor Documentation
BlockInput::BlockInput (const AnsiString aName)
Konstruktor
Parameters:
aName nazwa wejscia bloku
Definition at line 20 of file BlockInput.cpp.
BlockInput::BlockInput (const BlockInput & kopia)
Konstruktor kopiujacy
Parameters:
copy element ktory zostanie skopiowany
Definition at line 24 of file BlockInput.cpp.
References allowedTypes, and inputType.
BlockInput::~BlockInput ()
Destruktor
Definition at line 30 of file BlockInput.cpp.
Member Function Documentation
bool BlockInput::connect (const AnsiString aName)
Realizuje polaczenia miêdzy blokami.
Parameters:
aName nazwa obiektu z ktorym bedzie polaczone wejscie.
Returns: poprawnosc przeprowadzonej operajci.
Definition at line 3 of file BlockInput.cpp.
References inputType.
Referenced by PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and PIWOEngine::MakeConnection().
AnsiString & BlockInput::getConnectedType ()
Pobiera typ polaczenia.
Returns: nazwa typu polaczenia.
Definition at line 15 of file BlockInput.cpp.
References inputType.
Referenced by VisualBlock::updateVisualComponents().
void BlockInput::disconnect ()
rozlacza bloki
Definition at line 10 of file BlockInput.cpp.
References inputType.
Referenced by PIWOEngine::DeleteSelectedConnection(), PIWOEngine::OnVisualBlockInputSelected(), and PIWOEngine::OnVisualBlockOutputSelected().
Member Data Documentation
AnsiString BlockInput::inputType [private]
Definition at line 18 of file BlockInput.h.
Referenced by BlockInput(), connect(), disconnect(), and getConnectedType().
vector<AnsiString> BlockInput::allowedTypes
lista dozwolonych typow które moga zostac podane na wejscie
Definition at line 37 of file BlockInput.h.
Referenced by BlockInput(), PIWOEngine::loadFromFile(), PIWOEngine::MakeConnection(), Connection::update(), and VisualBlock::updateVisualComponents().
The documentation for this class was generated from the following files:
/PIWO/Program/engine/BlockInput.h
/PIWO/Program/engine/BlockInput.cpp