/PIWO/Program/gui/PIWOEngine.h File Reference
#include <SysUtils.hpp>
#include <Classes.hpp>
#include <Controls.hpp>
#include <Forms.hpp>
#include `../brige/PluginContener.h`
#include `VisualBlock.h`
#include `Connection.h`
#include `history.h`
Classes
class PIWOEngine
Defines
#define PIWOEngineH
#define PIWOMAINCLASSTYPE TScrollBox
Typedefs
typedef const AnsiString
typedef void(__closure * PIWOEngine_RunProgress)(TObject *, const AnsiString, const double)
Functions
typedef void (__closure *PIWOEngine_Log)(TObject *
void putString (const AnsiString &str, TStream &stream)
void putInt (const int i, TStream &stream)
AnsiString getString (TStream &stream)
int getInt (TStream &stream)
Define Documentation
#define PIWOEngineH
Definition at line 2 of file PIWOEngine.h.
#define PIWOMAINCLASSTYPE TScrollBox
Definition at line 13 of file PIWOEngine.h.
Referenced by VisualBlock::BlockMouseDown(), VisualBlock::BlockMouseUp(), and PIWOEngine::PIWOEngine().
Typedef Documentation
typedef const AnsiString
Definition at line 15 of file PIWOEngine.h.
typedef void(__closure * PIWOEngine_RunProgress)(TObject *, const AnsiString, const double)
Definition at line 16 of file PIWOEngine.h.
Function Documentation
int getInt (TStream & stream)
Pobiera integer z stream
Parameters:
stream stream
Returns: integer
Definition at line 2528 of file PIWOEngine.cpp.
Referenced by PIWOEngine::loadFromFile().
AnsiString getString (TStream & stream)
Pobiera string z stream
Parameters:
stream stream
Returns: string
Definition at line 2515 of file PIWOEngine.cpp.
Referenced by PIWOEngine::loadFromFile().
void putInt (const int i, TStream & stream)
Zapisuje integer do stream
Parameters:
i integer
stream stream
Definition at line 2510 of file PIWOEngine.cpp.
Referenced by PIWOEngine::saveToFile().
void putString (const AnsiString & str, TStream & stream)
Zapisuje string do stream
Parameters:
str string
stream stream
Definition at line 2502 of file PIWOEngine.cpp.
Referenced by PIWOEngine::saveToFile().
typedef void (__closure * PIWOEngine_Log)