THistory Class Reference
#include <history.h>
Public Member Functions
void __fastcall TreeView1Deletion (TObject *Sender, TTreeNode *Node)
void __fastcall BitBtn2Click (TObject *Sender)
void __fastcall TreeView1Click (TObject *Sender)
void __fastcall CreateParams (Controls::TCreateParams &Params)
__fastcall THistory (TComponent *Owner)
__fastcall ~THistory ()
void refresh (BlockElement *toShow)
Public Attributes
TStatusBar * StatusBar1
TImageList * ImageList1
TPanel * Panel1
TTreeView * TreeView1
TPanel * Panel2
TBitBtn * BitBtn2
TLabel * Label1
VisualBlock * block
PluginContener * plugins
Private Attributes
vector< TForm * > windows
TFrame * showFrame
unsigned int count
Detailed Description
Klasa jest oknem histori
Definition at line 24 of file history.h.
Constructor & Destructor Documentation
__fastcall THistory::THistory (TComponent * Owner)
Konstruktor
Parameters:
Owner wskaznik do klasy bedacej wlascicielem dla tej
Definition at line 8 of file history.cpp.
References count, and showFrame.
__fastcall THistory::~THistory ()
Destruktor
Definition at line 15 of file history.cpp.
References TreeView1.
Member Function Documentation
void __fastcall THistory::TreeView1Deletion (TObject * Sender, TTreeNode * Node)
Definition at line 161 of file history.cpp.
void __fastcall THistory::BitBtn2Click (TObject * Sender)
Definition at line 171 of file history.cpp.
References refresh().
void __fastcall THistory::TreeView1Click (TObject * Sender)
Definition at line 178 of file history.cpp.
References refresh(), showFrame, and TreeView1.
void __fastcall THistory::CreateParams (Controls::TCreateParams & Params)
Definition at line 201 of file history.cpp.
void THistory::refresh (BlockElement * toShow)
Metoda wyswietla liste historii, i pokazuje ostatnia historie dla parametru toShow
Parameters:
toShow wskaznik do niskopoziomowego wejscia/wyjscia bloku, jesli NULL to przy wywolaniu zadne `okno` nie zostanie pokazane
Definition at line 20 of file history.cpp.
References block, count, VisualBlock::getTitle(), PluginContener::getType(), TypeDLL::getType(), VisualBlock::history, Label1, plugins, TypeDLL::show(), showFrame, and TreeView1.
Referenced by BitBtn2Click(), PIWOEngine::OnVisualBlockInputHistoryClick(), PIWOEngine::OnVisualBlockOutputHistoryClick(), and TreeView1Click().
Member Data Documentation
TStatusBar* THistory::StatusBar1
Definition at line 27 of file history.h.
TImageList* THistory::ImageList1
Definition at line 28 of file history.h.
TPanel* THistory::Panel1
Definition at line 29 of file history.h.
TTreeView* THistory::TreeView1
Definition at line 30 of file history.h.
Referenced by refresh(), TreeView1Click(), and ~THistory().
TPanel* THistory::Panel2
Definition at line 31 of file history.h.
TBitBtn* THistory::BitBtn2
Definition at line 32 of file history.h.
TLabel* THistory::Label1
Definition at line 33 of file history.h.
Referenced by refresh().
vector<TForm*> THistory::windows [private]
Definition at line 39 of file history.h.
TFrame* THistory::showFrame [private]
Definition at line 40 of file history.h.
Referenced by refresh(), THistory(), and TreeView1Click().
unsigned int THistory::count [private]
Definition at line 41 of file history.h.
Referenced by refresh(), and THistory().
VisualBlock* THistory::block
Wskaznik do wizualnego bloku, musi byc ustawiony przed refresh
Definition at line 55 of file history.h.
Referenced by PIWOEngine::OnVisualBlockInputHistoryClick(), PIWOEngine::OnVisualBlockOutputHistoryClick(), and refresh().
PluginContener* THistory::plugins
Wskaznik do kontenera pluginow, musi byc ustawione przed refresh
Definition at line 59 of file history.h.
Referenced by PIWOEngine::OnVisualBlockInputHistoryClick(), PIWOEngine::OnVisualBlockOutputHistoryClick(), and refresh().
The documentation for this class was generated from the following files:
/PIWO/Program/gui/history.h
/PIWO/Program/gui/history.cpp