PluginContener Class Reference
#include <PluginContener.h>
Public Member Functions
PluginContener ()
~PluginContener ()
bool LoadData (AnsiString blockDir, AnsiString typesDir, TMainMenu &menu, TImageList &images, int upId, int downId, int functionIcon, int folderIcon)
TypeDLL * addType (const AnsiString &fileDLL)
FunctionDLL * addFunction (const AnsiString &fileDLL)
TypeDLL * getType (const AnsiString &type)
FunctionDLL * getFunction (const AnsiString &name)
void setMenuItemsStatus (bool enabled)
Public Attributes
PluginContener_OnProgress OnLoadingProgress
FunctionDLL_onClick OnFunctionAddRequest
Private Member Functions
int SearchDirectory (std::vector< AnsiString > &refvecFiles, const AnsiString &refcstrRootDirectory, const AnsiString &refcstrExtension, bool bSearchSubdirectories=true)
void AddMenus (FunctionDLL *info, TMainMenu &menu, TImageList &images, int upId, int downId, int functionIcon, int folderIcon)
void OnFunctionClick (void *Sender)
Private Attributes
vector< TypeDLL * > listOfType
vector< FunctionDLL * > listOfFunction
vector< TMenuItem * > menuItems
Detailed Description
Klasa pojemnik przechowujaca pluginy
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 20 of file PluginContener.h.
Constructor & Destructor Documentation
PluginContener::PluginContener ()
Konstuktor domyslny
Definition at line 30 of file PluginContener.cpp.
References OnFunctionAddRequest, and OnLoadingProgress.
PluginContener::~PluginContener ()
Destruktor
Definition at line 36 of file PluginContener.cpp.
References listOfFunction, and listOfType.
Member Function Documentation
int PluginContener::SearchDirectory (std::vector< AnsiString > & refvecFiles, const AnsiString & refcstrRootDirectory, const AnsiString & refcstrExtension, bool bSearchSubdirectories = true) [private]
Definition at line 144 of file PluginContener.cpp.
Referenced by LoadData().
void PluginContener::AddMenus (FunctionDLL * info, TMainMenu & menu, TImageList & images, int upId, int downId, int functionIcon, int folderIcon) [private]
Definition at line 71 of file PluginContener.cpp.
References FunctionDLL::category, FunctionDLL::description, FunctionDLL::fullName, menuItems, FunctionDLL::name, FunctionDLL::OnClick(), and FunctionDLL::picture.
Referenced by LoadData().
void PluginContener::OnFunctionClick (void * Sender) [private]
Definition at line 196 of file PluginContener.cpp.
References OnFunctionAddRequest.
Referenced by LoadData().
bool PluginContener::LoadData (AnsiString blockDir, AnsiString typesDir, TMainMenu & menu, TImageList & images, int upId, int downId, int functionIcon, int folderIcon)
Metoda przeszukuje podfoldery w poszukiwaniu plikow typow ii plikow funkcji, laduje je i tworzy dla nich menu
Parameters:
blockDir folder zawierajacy dll funkcji
typesDir folder zawierajacy dll typu
menu referencja do obiektu menu do ktorego maja zostac dodane nowe mena
images lista obrazkow (kontener) powiazany z tym menu
upId identyfikator ustawiony w popredzajacych menach - GroupId
downId identyfikator ustawiony w nastepnych menach - GroupId
functionIcon domyslny nr ikony dla funkcji
folderIcon domyslny nr ikony dla kategori
Returns: true gdy zaladowano chodz jeden plugin
Definition at line 202 of file PluginContener.cpp.
References addFunction(), AddMenus(), addType(), FunctionDLL::FunctionAddRequest, TypeDLL::getType(), OnFunctionClick(), OnLoadingProgress, and SearchDirectory().
Referenced by TForm1::FormCreate().
TypeDLL * PluginContener::addType (const AnsiString & fileDLL)
Laduje i dodaje dll typu do kontenera.
Parameters:
fileDLL sciezka do pliku
Returns: NULL lub wskaznik do klsy TypeDLL
Definition at line 3 of file PluginContener.cpp.
References listOfType.
Referenced by LoadData().
FunctionDLL * PluginContener::addFunction (const AnsiString & fileDLL)
Laduje i dodaje dll funkcji do kontenera.
Parameters:
fileDLL sciezka do pliku
Returns: NULL lub wskaznik do klasy FunctionDLL
Definition at line 17 of file PluginContener.cpp.
References listOfFunction.
Referenced by LoadData().
TypeDLL * PluginContener::getType (const AnsiString & type)
Zwraca klase ktora zaladowala odpowiedni typ
Parameters:
type nazwa typu
Returns: klasa TypeDLL
Definition at line 53 of file PluginContener.cpp.
References listOfType.
Referenced by THistory::refresh(), and PIWOEngine::runBlock().
FunctionDLL * PluginContener::getFunction (const AnsiString & name)
Zwraca klase ktora zaladowala odpowiednia funkcje
Parameters:
name nazwa funkcji
Returns: klasa FunctionDLL
Definition at line 62 of file PluginContener.cpp.
References listOfFunction.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), PIWOEngine::OnVisualBlockConfigClick(), PIWOEngine::runBlock(), and PIWOEngine::validateBlock().
void PluginContener::setMenuItemsStatus (bool enabled)
Blokuje lub odblokowuje wszystkie pozycje w menu ladowanym dynamicznie
Parameters:
enabled true-odblokowane, false-zablokowane
Definition at line 245 of file PluginContener.cpp.
References menuItems.
Referenced by TForm1::blockMenu().
Member Data Documentation
vector<TypeDLL*> PluginContener::listOfType [private]
Definition at line 23 of file PluginContener.h.
Referenced by addType(), getType(), and ~PluginContener().
vector<FunctionDLL*> PluginContener::listOfFunction [private]
Definition at line 24 of file PluginContener.h.
Referenced by addFunction(), getFunction(), and ~PluginContener().
vector<TMenuItem*> PluginContener::menuItems [private]
Definition at line 31 of file PluginContener.h.
Referenced by AddMenus(), and setMenuItemsStatus().
PluginContener_OnProgress PluginContener::OnLoadingProgress
Event
Definition at line 36 of file PluginContener.h.
Referenced by TForm1::FormCreate(), LoadData(), and PluginContener().
FunctionDLL_onClick PluginContener::OnFunctionAddRequest
Event
Definition at line 40 of file PluginContener.h.
Referenced by TForm1::FormCreate(), OnFunctionClick(), and PluginContener().
The documentation for this class was generated from the following files:
/PIWO/Program/brige/PluginContener.h
/PIWO/Program/brige/PluginContener.cpp