BlockElement Class Reference
#include <BlockElement.h>
Public Member Functions
BlockElement (const AnsiString aName)
BlockElement (const BlockElement &block)
~BlockElement ()
AnsiString & getDescription ()
int getErrorCode ()
AnsiString & getErrorDescription ()
AnsiString & getName ()
TypeConfig * getObject ()
void setDescription (const AnsiString aDescription)
void setErrorDescription (const AnsiString aErrorDescription)
void setErrorCode (int aError)
void setObject (const TypeConfig &aData)
void clearObject ()
Protected Attributes
AnsiString description
int errorCode
AnsiString errorDescription
TypeConfig * object
AnsiString name
Detailed Description
BlockElement - Klasa reprezentujaca wejscia/wyjscia miedzy blokami, zawiera - nazwe, opis, stan - czy jest poprawnie podlaczony (errorCode)
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 18 of file BlockElement.h.
Constructor & Destructor Documentation
BlockElement::BlockElement (const AnsiString aName)
Konstruktor
Parameters:
aName nazwa tworzonego wejscia/wyjœcia
Definition at line 3 of file BlockElement.cpp.
References name.
BlockElement::BlockElement (const BlockElement & block)
Konstruktor
Parameters:
aName nazwa tworzonego wejscia/wyjœcia
Definition at line 9 of file BlockElement.cpp.
References description, errorCode, errorDescription, name, and object.
BlockElement::~BlockElement ()
Destruktor
Definition at line 21 of file BlockElement.cpp.
References object.
Member Function Documentation
AnsiString & BlockElement::getDescription ()
Pobiera opis.
Returns: AnsiString opis wejscia/wyjœcia.
Definition at line 26 of file BlockElement.cpp.
References description.
Referenced by PIWOEngine::CancelCustomizationOnSelectedConnections(), PIWOEngine::DeleteSelectedConnection(), PIWOEngine::MakeConnection(), PIWOEngine::OnConnectionSelect(), PIWOEngine::OnVisualBlockInputHistoryClick(), PIWOEngine::OnVisualBlockInputSelected(), PIWOEngine::OnVisualBlockOutputHistoryClick(), PIWOEngine::OnVisualBlockOutputSelected(), PIWOEngine::UnselectSelectedConnection(), Connection::update(), and VisualBlock::updateVisualComponents().
int BlockElement::getErrorCode ()
Pobiera kod bledu. int kod bledu.
Definition at line 31 of file BlockElement.cpp.
References errorCode.
Referenced by Connection::update(), VisualBlock::updateVisualComponents(), and PIWOEngine::validateBlock().
AnsiString & BlockElement::getErrorDescription ()
Pobiera Opis bledu
Returns: AnsiString - Opis bledu.
Definition at line 36 of file BlockElement.cpp.
References errorDescription.
Referenced by Connection::update(), VisualBlock::updateVisualComponents(), and PIWOEngine::validateBlock().
AnsiString & BlockElement::getName ()
Pobiera nazwe obiektu.
Returns: AnsiString nazwa obiektu.
Definition at line 41 of file BlockElement.cpp.
References name.
Referenced by PIWOEngine::OnVisualBlockInputHistoryClick(), and PIWOEngine::OnVisualBlockOutputHistoryClick().
TypeConfig * BlockElement::getObject ()
Pobiera Konfiguracje bloku.
Returns: TypeConfig konfiguracja bloku.
Definition at line 46 of file BlockElement.cpp.
References object.
Referenced by PIWOEngine::runBlock().
void BlockElement::setDescription (const AnsiString aDescription)
Ustawia opis.
Parameters:
aDescription - ustawiany opis.
Definition at line 51 of file BlockElement.cpp.
References description.
Referenced by PIWOEngine::loadFromFile().
void BlockElement::setErrorDescription (const AnsiString aErrorDescription)
Ustawia opis bledu.
Parameters:
aErrorDescription - ustawiany opis bledu.
Definition at line 56 of file BlockElement.cpp.
References errorDescription.
Referenced by PIWOEngine::loadFromFile().
void BlockElement::setErrorCode (int aError)
Ustawia kod blad.
Parameters:
aError - ustawiany kod,0-ok, 1-warrning, 2-error.
Definition at line 61 of file BlockElement.cpp.
References errorCode.
Referenced by PIWOEngine::loadFromFile().
void BlockElement::setObject (const TypeConfig & aData)
Ustawia obiekt.
Parameters:
aData - ustawiany obiekt.
Definition at line 66 of file BlockElement.cpp.
References object.
void BlockElement::clearObject ()
Usuwa obiekt.
Definition at line 72 of file BlockElement.cpp.
References object.
Member Data Documentation
AnsiString BlockElement::description [protected]
Definition at line 21 of file BlockElement.h.
Referenced by BlockElement(), getDescription(), and setDescription().
int BlockElement::errorCode [protected]
Definition at line 22 of file BlockElement.h.
Referenced by BlockElement(), getErrorCode(), and setErrorCode().
AnsiString BlockElement::errorDescription [protected]
Definition at line 23 of file BlockElement.h.
Referenced by BlockElement(), getErrorDescription(), and setErrorDescription().
TypeConfig* BlockElement::object [protected]
Definition at line 24 of file BlockElement.h.
Referenced by BlockElement(), clearObject(), getObject(), setObject(), and ~BlockElement().
AnsiString BlockElement::name [protected]
Definition at line 25 of file BlockElement.h.
Referenced by BlockElement(), and getName().
The documentation for this class was generated from the following files:
/PIWO/Program/engine/BlockElement.h
/PIWO/Program/engine/BlockElement.cpp