VisualBlock Class Reference
#include <VisualBlock.h>
Public Member Functions
__fastcall VisualBlock (TComponent *Owner)
__fastcall ~VisualBlock ()
Position getInputPosition (BlockInput *object)
Position getOutputPosition (BlockOutput *object)
bool setConfigButtonGlyph (Graphics::TBitmap *bmp)
void setTitle (const AnsiString &s)
AnsiString getTitle ()
bool updateVisualComponents ()
bool updateHistory ()
void setSelected (bool status)
bool isSelected ()
void setStatusColor (TColor cl)
Public Attributes
Block block
AnsiString nameOfBlock
int numberOfBlock
bool runned
vectorBlockHistory history
vector< VisualInput * > leftInput
vector< VisualInput * > topInput
vector< VisualOutput * > rightOutput
vector< VisualOutput * > bottomOutput
VisualFunction OnConfigClick
VisualBlock_FunctionI OnVisualInputSelected
VisualBlock_FunctionO OnVisualOutputSelected
VisualBlock_FunctionHI OnVInputHistory
VisualBlock_FunctionHO OnVOutputHistory
VisualBlock_FunctionMove OnBlockMove
VisualFunction OnUnselect
VisualFunction OnSelect
VisualFunction OnSelectAdd
Private Member Functions
void __fastcall SpeedButtonClick (TObject *Sender)
void __fastcall InputSelected (TObject *Sender)
void __fastcall OutputSelected (TObject *Sender)
void InputShowHistory (TObject *Sender)
void OutputShowHistory (TObject *Sender)
void __fastcall BlockClick (TObject *Sender)
void __fastcall BlockMouseDown (TObject *Sender, TMouseButton Button, TShiftState Shift, int X, int Y)
void __fastcall BlockMouseUp (TObject *Sender, TMouseButton Button, TShiftState Shift, int X, int Y)
void __fastcall BlockMouseMove (TObject *Sender, TShiftState Shift, int X, int Y)
void resizeAll ()
Private Attributes
TSpeedButton * configButton
TLabel * title
TPanel * status
bool selected
bool moving
bool button
TPoint oldPoint
Detailed Description
Klasa wyswietla caly bloczek
Definition at line 30 of file VisualBlock.h.
Constructor & Destructor Documentation
__fastcall VisualBlock::VisualBlock (TComponent * Owner)
Konstruktor
Parameters:
Owner klasa nadrzedna dla tej klasy
Definition at line 6 of file VisualBlock.cpp.
References BlockClick(), BlockMouseDown(), BlockMouseMove(), BlockMouseUp(), configButton, moving, nameOfBlock, numberOfBlock, OnBlockMove, OnSelect, OnSelectAdd, OnUnselect, OnVInputHistory, OnVisualInputSelected, OnVisualOutputSelected, OnVOutputHistory, runned, selected, SpeedButtonClick(), status, and title.
__fastcall VisualBlock::~VisualBlock ()
Destruktor
Definition at line 85 of file VisualBlock.cpp.
References bottomOutput, configButton, history, leftInput, rightOutput, status, title, and topInput.
Member Function Documentation
void __fastcall VisualBlock::SpeedButtonClick (TObject * Sender) [private]
Definition at line 190 of file VisualBlock.cpp.
References OnConfigClick.
Referenced by VisualBlock().
void __fastcall VisualBlock::InputSelected (TObject * Sender) [private]
Definition at line 487 of file VisualBlock.cpp.
References OnVisualInputSelected.
Referenced by updateVisualComponents().
void __fastcall VisualBlock::OutputSelected (TObject * Sender) [private]
Definition at line 493 of file VisualBlock.cpp.
References OnVisualOutputSelected.
Referenced by updateVisualComponents().
void VisualBlock::InputShowHistory (TObject * Sender) [private]
Definition at line 499 of file VisualBlock.cpp.
References OnVInputHistory.
Referenced by updateVisualComponents().
void VisualBlock::OutputShowHistory (TObject * Sender) [private]
Definition at line 505 of file VisualBlock.cpp.
References OnVOutputHistory.
Referenced by updateVisualComponents().
void __fastcall VisualBlock::BlockClick (TObject * Sender) [private]
Definition at line 529 of file VisualBlock.cpp.
References altDown(), ctrlDown(), moving, OnSelect, OnSelectAdd, OnUnselect, selected, and setSelected().
Referenced by VisualBlock().
void __fastcall VisualBlock::BlockMouseDown (TObject * Sender, TMouseButton Button, TShiftState Shift, int X, int Y) [private]
Definition at line 554 of file VisualBlock.cpp.
References BlockMouseMove(), BlockMouseUp(), button, moving, oldPoint, OnSelect, OnSelectAdd, PIWOMAINCLASSTYPE, selected, and setSelected().
Referenced by VisualBlock().
void __fastcall VisualBlock::BlockMouseUp (TObject * Sender, TMouseButton Button, TShiftState Shift, int X, int Y) [private]
Definition at line 601 of file VisualBlock.cpp.
References moving, and PIWOMAINCLASSTYPE.
Referenced by BlockMouseDown(), and VisualBlock().
void __fastcall VisualBlock::BlockMouseMove (TObject * Sender, TShiftState Shift, int X, int Y) [private]
Definition at line 609 of file VisualBlock.cpp.
References button, moving, oldPoint, and OnBlockMove.
Referenced by BlockMouseDown(), and VisualBlock().
void VisualBlock::resizeAll () [private]
Definition at line 411 of file VisualBlock.cpp.
References bottomOutput, leftInput, rightOutput, status, title, and topInput.
Referenced by updateVisualComponents().
Position VisualBlock::getInputPosition (BlockInput * object)
Pobiera pozycje wejscia do bloku
Parameters:
object wejscie
Returns: pozycja
Definition at line 122 of file VisualBlock.cpp.
References Position::direction, leftInput, topInput, and Position::xy.
Referenced by Connection::connectionOk(), and Connection::draw().
Position VisualBlock::getOutputPosition (BlockOutput * object)
Pobiera pozycje wyjscia z bloku
Parameters:
object wyjscia
Returns: pozycja
Definition at line 156 of file VisualBlock.cpp.
References bottomOutput, Position::direction, rightOutput, and Position::xy.
Referenced by Connection::connectionOk(), and Connection::draw().
bool VisualBlock::setConfigButtonGlyph (Graphics::TBitmap * bmp)
Ustawia nowy obrazek jako obrazek pokazujacy sie na przycusku konfiguracyjnym
Parameters:
bmp obrazek
Returns: true jesli operacja sie powiodla
Definition at line 197 of file VisualBlock.cpp.
References configButton.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), and PIWOEngine::loadFromFile().
void VisualBlock::setTitle (const AnsiString & s)
Ustawia tytul bloczka
Parameters:
s nowy tytul
Definition at line 204 of file VisualBlock.cpp.
References block, Block::title, and title.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), and PIWOEngine::loadFromFile().
AnsiString VisualBlock::getTitle ()
Pobiera aktualny tytul bloczka
Returns: tytul
Definition at line 211 of file VisualBlock.cpp.
References title.
Referenced by PIWOEngine::CancelCustomizationOnSelectedConnections(), PIWOEngine::DeleteSelectedConnection(), PIWOEngine::loadFromFile(), PIWOEngine::MakeConnection(), PIWOEngine::OnConnectionSelect(), PIWOEngine::OnVisualBlockConfigClick(), PIWOEngine::OnVisualBlockInputHistoryClick(), PIWOEngine::OnVisualBlockInputSelected(), PIWOEngine::OnVisualBlockOutputHistoryClick(), PIWOEngine::OnVisualBlockOutputSelected(), PIWOEngine::OnVisualBlockUnselect(), THistory::refresh(), PIWOEngine::runBlock(), PIWOEngine::UnselectSelectedConnection(), Connection::update(), and PIWOEngine::validateBlock().
bool VisualBlock::updateVisualComponents ()
Dostosowuje wizualne infomacje o bloczku do informacji zawartych w niskopoziomowej klasie Block.
Returns: false gdy wystapil blad
Definition at line 216 of file VisualBlock.cpp.
References BlockInput::allowedTypes, block, configButton, BlockInput::getConnectedType(), BlockElement::getDescription(), BlockElement::getErrorCode(), BlockElement::getErrorDescription(), BlockOutput::getOutputType(), VisualInput::input, Block::input, InputSelected(), InputShowHistory(), leftInput, VisualInputOutput::OnShowHistory, VisualOutput::output, Block::output, OutputSelected(), OutputShowHistory(), resizeAll(), rightOutput, status, and title.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), PIWOEngine::runBlock(), and PIWOEngine::validateBlock().
bool VisualBlock::updateHistory ()
Aktualizuje historie usuwajac z niej wszelkie przedawnione i nieaktualne dane
Definition at line 365 of file VisualBlock.cpp.
References block, bottomOutput, Block::getConfig(), BlockConfig::getRevision(), history, leftInput, rightOutput, and topInput.
Referenced by PIWOEngine::validateBlock().
void VisualBlock::setSelected (bool status)
Zaznacza/Odznacza blok
Parameters:
status true -zaznaczony, false - odznaczony
Definition at line 511 of file VisualBlock.cpp.
References selected.
Referenced by PIWOEngine::AddBlock(), BlockClick(), BlockMouseDown(), and PIWOEngine::OnVisualBlockUnselect().
bool VisualBlock::isSelected ()
Informuje o tym czy blok jest juz zaznaczony
Returns: true - zaznaczony, false - nie zaznaczony
Definition at line 524 of file VisualBlock.cpp.
References selected.
void VisualBlock::setStatusColor (TColor cl)
Ustawia kolor statusu bloczka - widniejacy do okola przycisku konfiguracyjnego
Parameters:
cl nowy kolor
Definition at line 639 of file VisualBlock.cpp.
References status.
Referenced by PIWOEngine::runBlock().
Member Data Documentation
TSpeedButton* VisualBlock::configButton [private]
Definition at line 33 of file VisualBlock.h.
Referenced by setConfigButtonGlyph(), updateVisualComponents(), VisualBlock(), and ~VisualBlock().
TLabel* VisualBlock::title [private]
Definition at line 34 of file VisualBlock.h.
Referenced by getTitle(), resizeAll(), setTitle(), updateVisualComponents(), VisualBlock(), and ~VisualBlock().
TPanel* VisualBlock::status [private]
Definition at line 35 of file VisualBlock.h.
Referenced by resizeAll(), setStatusColor(), updateVisualComponents(), VisualBlock(), and ~VisualBlock().
bool VisualBlock::selected [private]
Definition at line 36 of file VisualBlock.h.
Referenced by BlockClick(), BlockMouseDown(), isSelected(), setSelected(), and VisualBlock().
bool VisualBlock::moving [private]
Definition at line 37 of file VisualBlock.h.
Referenced by BlockClick(), BlockMouseDown(), BlockMouseMove(), BlockMouseUp(), and VisualBlock().
bool VisualBlock::button [private]
Definition at line 38 of file VisualBlock.h.
Referenced by BlockMouseDown(), and BlockMouseMove().
TPoint VisualBlock::oldPoint [private]
Definition at line 39 of file VisualBlock.h.
Referenced by BlockMouseDown(), and BlockMouseMove().
Block VisualBlock::block
Blok w wersji niskopoziomowej
Definition at line 54 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), PIWOEngine::OnVisualBlockConfigClick(), PIWOEngine::runBlock(), setTitle(), updateHistory(), updateVisualComponents(), and PIWOEngine::validateBlock().
AnsiString VisualBlock::nameOfBlock
Definition at line 55 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), PIWOEngine::OnVisualBlockConfigClick(), PIWOEngine::runBlock(), PIWOEngine::validateBlock(), and VisualBlock().
int VisualBlock::numberOfBlock
Definition at line 56 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and VisualBlock().
bool VisualBlock::runned
Informacja o tym czy blok zostal juz uruchomiony - zmienna pomocnicza, wewnetrzna
Definition at line 60 of file VisualBlock.h.
Referenced by PIWOEngine::runBlock(), and VisualBlock().
vectorBlockHistory VisualBlock::history
Historia bloku
Definition at line 64 of file VisualBlock.h.
Referenced by PIWOEngine::OnVisualBlockInputHistoryClick(), PIWOEngine::OnVisualBlockOutputHistoryClick(), THistory::refresh(), PIWOEngine::runBlock(), updateHistory(), and ~VisualBlock().
vector<VisualInput*> VisualBlock::leftInput
Lista wejsc do bloku z lewej strony
Definition at line 68 of file VisualBlock.h.
Referenced by getInputPosition(), resizeAll(), PIWOEngine::runBlock(), updateHistory(), updateVisualComponents(), and ~VisualBlock().
vector<VisualInput*> VisualBlock::topInput
Lista wejsc do bloku z gornej strony
Definition at line 72 of file VisualBlock.h.
Referenced by getInputPosition(), resizeAll(), PIWOEngine::runBlock(), updateHistory(), and ~VisualBlock().
vector<VisualOutput*> VisualBlock::rightOutput
Lista wyjsc z bloku z prawej strony
Definition at line 76 of file VisualBlock.h.
Referenced by getOutputPosition(), resizeAll(), PIWOEngine::runBlock(), updateHistory(), updateVisualComponents(), and ~VisualBlock().
vector<VisualOutput*> VisualBlock::bottomOutput
Lista wyjsc z bloku z dolnej strony
Definition at line 80 of file VisualBlock.h.
Referenced by getOutputPosition(), resizeAll(), PIWOEngine::runBlock(), updateHistory(), and ~VisualBlock().
VisualFunction VisualBlock::OnConfigClick
Event: gdy kliknieto przycisk konfiguracyjny
Definition at line 85 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and SpeedButtonClick().
VisualBlock_FunctionI VisualBlock::OnVisualInputSelected
Event: gdy kliknieto na wejscie bloku
Definition at line 89 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), InputSelected(), PIWOEngine::loadFromFile(), and VisualBlock().
VisualBlock_FunctionO VisualBlock::OnVisualOutputSelected
Event: gdy kliknieto na wyjscie bloku
Definition at line 93 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), OutputSelected(), and VisualBlock().
VisualBlock_FunctionHI VisualBlock::OnVInputHistory
Event: gdy kliknieto prawym przycuskiem na wejscie bloku
Definition at line 97 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), InputShowHistory(), PIWOEngine::loadFromFile(), and VisualBlock().
VisualBlock_FunctionHO VisualBlock::OnVOutputHistory
Event: gdy kliknieto prawym przyciskiem na wyjscie bloku
Definition at line 101 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), OutputShowHistory(), and VisualBlock().
VisualBlock_FunctionMove VisualBlock::OnBlockMove
Event: gdy przesunieto blok
Definition at line 105 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), BlockMouseMove(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and VisualBlock().
VisualFunction VisualBlock::OnUnselect
Event: gdy odznacozno blok
Definition at line 109 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), BlockClick(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and VisualBlock().
VisualFunction VisualBlock::OnSelect
Event: gdy gdy zaznacozno blok, ale zarzadano odznaczenia innych
Definition at line 113 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), BlockClick(), BlockMouseDown(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and VisualBlock().
VisualFunction VisualBlock::OnSelectAdd
Event: gdy zaznaczono blok
Definition at line 117 of file VisualBlock.h.
Referenced by PIWOEngine::AddBlock(), BlockClick(), BlockMouseDown(), PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), and VisualBlock().
The documentation for this class was generated from the following files:
/PIWO/Program/gui/VisualBlock.h
/PIWO/Program/gui/VisualBlock.cpp