BlockOutput Class Reference
#include <BlockOutput.h>
Public Member Functions
BlockOutput (const AnsiString aName)
BlockOutput (const BlockOutput &copy)
~BlockOutput ()
AnsiString & getOutputType ()
bool setOutputType (AnsiString aName)
Private Attributes
AnsiString outputType
Detailed Description
BlockInput - Klasa pojemnik przechowujaca wejscia i wyjscia bloku
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 15 of file BlockOutput.h.
Constructor & Destructor Documentation
BlockOutput::BlockOutput (const AnsiString aName)
Konstruktor
Parameters:
aName nazwa wyjscia.
Definition at line 3 of file BlockOutput.cpp.
BlockOutput::BlockOutput (const BlockOutput & copy)
Konstruktor kopiujacy.
Parameters:
copy obiekt ktory zostanie skopiowany
Definition at line 7 of file BlockOutput.cpp.
References outputType.
BlockOutput::~BlockOutput ()
Destruktor
Definition at line 12 of file BlockOutput.cpp.
Member Function Documentation
AnsiString & BlockOutput::getOutputType ()
Zwraca typ wyjscia.
Returns: AnsiString typ wyjscia
Definition at line 16 of file BlockOutput.cpp.
References outputType.
Referenced by PIWOEngine::DuplcateSelectedBlocks(), PIWOEngine::loadFromFile(), PIWOEngine::MakeConnection(), Connection::update(), VisualBlock::updateVisualComponents(), and PIWOEngine::validateBlock().
bool BlockOutput::setOutputType (AnsiString aName)
Ustawia typ wyjscia.
Parameters:
aName typ wyjscia.
Returns: poprawnosc wykonanej operacji
Definition at line 21 of file BlockOutput.cpp.
References outputType.
Referenced by PIWOEngine::loadFromFile().
Member Data Documentation
AnsiString BlockOutput::outputType [private]
Definition at line 18 of file BlockOutput.h.
Referenced by BlockOutput(), getOutputType(), and setOutputType().
The documentation for this class was generated from the following files:
/PIWO/Program/engine/BlockOutput.h
/PIWO/Program/engine/BlockOutput.cpp