/PIWO/Program/gui/PIWOEngine.cpp File Reference
#include <vcl.h>
#include `PIWOEngine.h`
#include `BlockValidateInputElement.h`
#include `BlockValidateOutputElement.h`
Functions
void putString (const AnsiString &str, TStream &stream)
void putInt (const int i, TStream &stream)
AnsiString getString (TStream &stream)
int getInt (TStream &stream)
Function Documentation
int getInt (TStream & stream)
Pobiera integer z stream
Parameters:
stream stream
Returns: integer
Definition at line 2528 of file PIWOEngine.cpp.
Referenced by PIWOEngine::loadFromFile().
AnsiString getString (TStream & stream)
Pobiera string z stream
Parameters:
stream stream
Returns: string
Definition at line 2515 of file PIWOEngine.cpp.
Referenced by PIWOEngine::loadFromFile().
void putInt (const int i, TStream & stream)
Zapisuje integer do stream
Parameters:
i integer
stream stream
Definition at line 2510 of file PIWOEngine.cpp.
Referenced by PIWOEngine::saveToFile().
void putString (const AnsiString & str, TStream & stream)
Zapisuje string do stream
Parameters:
str string
stream stream
Definition at line 2502 of file PIWOEngine.cpp.
Referenced by PIWOEngine::saveToFile().