BlockConfig Class Reference
#include <BlockConfig.h>
Public Member Functions
BlockConfig ()
BlockConfig (const BlockConfig &aCopy)
BlockConfig (TStream &stream)
~BlockConfig ()
bool addString (const AnsiString aName, const AnsiString aValue)
bool addBoolean (const AnsiString aName, bool aValue)
bool addInt (const AnsiString aName, int aValue)
bool addDouble (const AnsiString aName, double aValue)
bool addBitmap (const AnsiString aName, const Graphics::TBitmap &aValue)
bool addStream (const AnsiString aName, TStream &aValue)
bool setString (const AnsiString aName, const AnsiString aValue)
bool setBoolean (const AnsiString aName, bool aValue)
bool setInt (const AnsiString aName, int aValue)
bool setDouble (const AnsiString aName, double aValue)
bool setBitmap (const AnsiString aName, const Graphics::TBitmap &aValue)
bool setStream (const AnsiString aName, TStream &aValue)
const AnsiString & getString (const AnsiString aName)
bool getBoolean (const AnsiString aName)
int getInt (const AnsiString aName)
double getDouble (const AnsiString aName)
const Graphics::TBitmap & getBitmap (const AnsiString aName)
const TStream & getStream (const AnsiString aName)
bool isString (const AnsiString aName)
bool isBoolean (const AnsiString aName)
bool isInt (const AnsiString aName)
bool isDouble (const AnsiString aName)
bool isBitmap (const AnsiString aName)
bool isStream (const AnsiString aName)
const AnsiString & getType (const AnsiString aName)
bool isExist (const AnsiString aName)
bool remove (const AnsiString aName)
bool saveToStream (TStream &aWhere)
bool loadFromStream (TStream &aFrom)
bool isChanged ()
void setChangedFalse ()
unsigned long getRevision ()
void clear ()
Protected Member Functions
Item * getItem (const AnsiString aName)
bool loadFromStream2 (TStream &aFrom)
bool saveToStream2 (TStream &aWhere)
void copyFrom (const BlockConfig &aCopy)
Protected Attributes
vector< Item * > map
bool changed
unsigned long revision
Detailed Description
BlockConfig - Klasa przechowujaca dane w postaci hashmapy, uzywana jako miejsce do przechowywania konfiguracji dowolnego bloczka.
Author: Piotr
Date: 2008.11.25
Version: 0.1
Definition at line 18 of file BlockConfig.h.
Constructor & Destructor Documentation
BlockConfig::BlockConfig ()
Konstruktor.
Definition at line 12 of file BlockConfig.cpp.
References changed, and revision.
BlockConfig::BlockConfig (const BlockConfig & aCopy)
Konsrutkor Kopiujacy
Parameters:
aCopy obiekt ktory zostanie skopiowany
Definition at line 72 of file BlockConfig.cpp.
References changed, copyFrom(), and revision.
BlockConfig::BlockConfig (TStream & stream)
Konstruktor kopiuj±cy z TStream
Parameters:
stream Stream z ktorego ma zostac wczytany.
Definition at line 18 of file BlockConfig.cpp.
References changed, loadFromStream(), and revision.
BlockConfig::~BlockConfig ()
Destruktor
Definition at line 79 of file BlockConfig.cpp.
References clear().
Member Function Documentation
Item * BlockConfig::getItem (const AnsiString aName) [protected]
Definition at line 3 of file BlockConfig.cpp.
References map.
Referenced by getBitmap(), getBoolean(), getDouble(), getInt(), getStream(), getString(), getType(), isBitmap(), isBoolean(), isDouble(), isExist(), isInt(), isStream(), isString(), remove(), setBitmap(), setBoolean(), setDouble(), setInt(), setStream(), and setString().
bool BlockConfig::loadFromStream2 (TStream & aFrom) [protected]
Definition at line 454 of file BlockConfig.cpp.
References map.
Referenced by TypeConfig::loadFromStream(), and loadFromStream().
bool BlockConfig::saveToStream2 (TStream & aWhere) [protected]
Definition at line 392 of file BlockConfig.cpp.
References getType(), and map.
Referenced by TypeConfig::saveToStream(), and saveToStream().
void BlockConfig::copyFrom (const BlockConfig & aCopy) [protected]
Definition at line 25 of file BlockConfig.cpp.
References map.
Referenced by BlockConfig().
bool BlockConfig::addString (const AnsiString aName, const AnsiString aValue)
Dodaje obiekt typu string (aTyp) na listê pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 117 of file BlockConfig.cpp.
References changed, isExist(), map, and revision.
bool BlockConfig::addBoolean (const AnsiString aName, bool aValue)
Dodaje obiekt typu Boolean (aTyp) na listê pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 127 of file BlockConfig.cpp.
References changed, isExist(), map, and revision.
bool BlockConfig::addInt (const AnsiString aName, int aValue)
Dodaje obiekt typu int (aTyp) na listê pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 138 of file BlockConfig.cpp.
References changed, isExist(), map, and revision.
bool BlockConfig::addDouble (const AnsiString aName, double aValue)
Dodaje obiekt typu double (aTyp) na listê pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 149 of file BlockConfig.cpp.
References changed, isExist(), map, and revision.
bool BlockConfig::addBitmap (const AnsiString aName, const Graphics::TBitmap & aValue)
Dodaje obiekt typu TBitmap (aTyp) na listê pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 160 of file BlockConfig.cpp.
References changed, isExist(), map, and revision.
bool BlockConfig::addStream (const AnsiString aName, TStream & aValue)
Dodaje obiekt typu TStream (aTyp) na listê pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 171 of file BlockConfig.cpp.
References changed, isExist(), map, and revision.
bool BlockConfig::setString (const AnsiString aName, const AnsiString aValue)
Zmienia obiekt typu string (aTyp) na liscie pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 182 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), revision, and Item::setObject().
bool BlockConfig::setBoolean (const AnsiString aName, bool aValue)
Zmienia obiekt typu boolean (aTyp) na liscie pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 193 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), revision, and Item::setObject().
bool BlockConfig::setInt (const AnsiString aName, int aValue)
Zmienia obiekt typu int (aTyp) na liscie pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 205 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), revision, and Item::setObject().
bool BlockConfig::setDouble (const AnsiString aName, double aValue)
Zmienia obiekt typu double (aTyp) na liscie pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 217 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), revision, and Item::setObject().
bool BlockConfig::setBitmap (const AnsiString aName, const Graphics::TBitmap & aValue)
Zmienia obiekt typu TBitmap (aTyp) na liscie pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 229 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), revision, and Item::setObject().
bool BlockConfig::setStream (const AnsiString aName, TStream & aValue)
Zmienia obiekt typu TStream (aTyp) na liscie pod nazwa aName.
Parameters:
aName nazwa pod jaka obiekt ma widniesc na liœcie
aValue dane jakie maja zostac wrzucone na liste
Returns: zwraca true jesli obiekt zostal dodany
Definition at line 241 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), revision, and Item::setObject().
const AnsiString & BlockConfig::getString (const AnsiString aName)
Pobiera obiekt typu string z listy pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: wartosc danego obiektu
Definition at line 253 of file BlockConfig.cpp.
References getItem(), Item::getObject(), and Item::getType().
bool BlockConfig::getBoolean (const AnsiString aName)
Pobiera obiekt typu boolean (aTyp) z listy pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: wartosc danego obiektu
Definition at line 260 of file BlockConfig.cpp.
References getItem(), Item::getObject(), and Item::getType().
int BlockConfig::getInt (const AnsiString aName)
Pobiera obiekt typu int (aTyp) z listy pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: wartosc danego obiektu
Definition at line 267 of file BlockConfig.cpp.
References getItem(), Item::getObject(), and Item::getType().
double BlockConfig::getDouble (const AnsiString aName)
Pobiera obiekt typu double (aTyp) z listy pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: wartosc danego obiektu
Definition at line 274 of file BlockConfig.cpp.
References getItem(), Item::getObject(), and Item::getType().
const Graphics::TBitmap & BlockConfig::getBitmap (const AnsiString aName)
Pobiera obiekt typu TBitmap (aTyp) z listy pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: wartosc danego obiektu
Definition at line 281 of file BlockConfig.cpp.
References getItem(), Item::getObject(), and Item::getType().
const TStream & BlockConfig::getStream (const AnsiString aName)
Pobiera obiekt typu Stream (aTyp) z listy pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: wartosc danego obiektu
Definition at line 288 of file BlockConfig.cpp.
References getItem(), Item::getObject(), and Item::getType().
bool BlockConfig::isString (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName jest typu String.
Parameters:
aName nazwa obiektu
Returns: ture - jezeli jest to ten sam typ false - jezeli nie.
Definition at line 295 of file BlockConfig.cpp.
References getItem(), and Item::getType().
bool BlockConfig::isBoolean (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName jest typu booleand.
Parameters:
aName nazwa obiektu
Returns: ture - jezeli jest to ten sam typ false - jezeli nie.
Definition at line 300 of file BlockConfig.cpp.
References getItem(), and Item::getType().
bool BlockConfig::isInt (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName jest typu int.
Parameters:
aName nazwa obiektu
Returns: trure - jezeli jest to ten sam typ false - jezeli nie.
Definition at line 305 of file BlockConfig.cpp.
References getItem(), and Item::getType().
bool BlockConfig::isDouble (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName jest typu Double.
Parameters:
aName nazwa obiektu
Returns: true - jezeli jest to ten sam typ false - jezeli nie.
Definition at line 310 of file BlockConfig.cpp.
References getItem(), and Item::getType().
bool BlockConfig::isBitmap (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName jest typu TBitmap.
Parameters:
aName nazwa obiektu
Returns: true - jezeli jest to ten sam typ false - jezeli nie.
Definition at line 315 of file BlockConfig.cpp.
References getItem(), and Item::getType().
bool BlockConfig::isStream (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName jest typu TStream.
Parameters:
aName nazwa obiektu
Returns: true - jezeli jest to ten sam typ false - jezeli nie.
Definition at line 320 of file BlockConfig.cpp.
References getItem(), and Item::getType().
const AnsiString & BlockConfig::getType (const AnsiString aName)
Zwraca typ danego obiekut.
Parameters:
aName nazwa obiektu
Returns: string okreslajacy typ.
Definition at line 325 of file BlockConfig.cpp.
References getItem(), and Item::getType().
Referenced by clear(), and saveToStream2().
bool BlockConfig::isExist (const AnsiString aName)
Sprawdza czy obiekt pod nazwa aName istnieje.
Parameters:
aName nazwa obiektu
Returns: true - jezeli isntieje false - jezeli nie.
Definition at line 330 of file BlockConfig.cpp.
References getItem().
Referenced by addBitmap(), addBoolean(), addDouble(), addInt(), addStream(), and addString().
bool BlockConfig::remove (const AnsiString aName)
Usuwa obiekt pod nazwa aName.
Parameters:
aName nazwa obiektu
Returns: true - jezeli zostal usuniety false - jezeli nie.
Definition at line 342 of file BlockConfig.cpp.
References changed, getItem(), Item::getObject(), Item::getType(), map, and revision.
bool BlockConfig::saveToStream (TStream & aWhere)
Zapisuje listê obiektow do strumienia.
Parameters:
aWhere strumien w ktorym zostana zapisane informacje.
Returns: true - jezeli operacja sie powiodla false - jezeli nie.
Reimplemented in TypeConfig.
Definition at line 444 of file BlockConfig.cpp.
References saveToStream2().
bool BlockConfig::loadFromStream (TStream & aFrom)
Odczytuje infomracjê o obiektach na liscie z strumienia
Parameters:
aName nazwa obiektu
Returns: true - jezeli operacja sie powiodla false - jezeli nie.
Reimplemented in TypeConfig.
Definition at line 543 of file BlockConfig.cpp.
References clear(), and loadFromStream2().
Referenced by BlockConfig(), and PIWOEngine::loadFromFile().
bool BlockConfig::isChanged ()
Definition at line 553 of file BlockConfig.cpp.
References changed.
void BlockConfig::setChangedFalse ()
zeruje flage changed
Definition at line 558 of file BlockConfig.cpp.
References changed.
unsigned long BlockConfig::getRevision ()
zwraca wersje (jest inkrementowana przy wykonywaniu dowolnych zmian)
Definition at line 563 of file BlockConfig.cpp.
References revision.
Referenced by PIWOEngine::OnVisualBlockConfigClick(), PIWOEngine::runBlock(), and VisualBlock::updateHistory().
void BlockConfig::clear ()
czyszczenie listy
Definition at line 84 of file BlockConfig.cpp.
References getType(), and map.
Referenced by TypeConfig::loadFromStream(), loadFromStream(), and ~BlockConfig().
Member Data Documentation
vector<Item*> BlockConfig::map [protected]
Definition at line 21 of file BlockConfig.h.
Referenced by addBitmap(), addBoolean(), addDouble(), addInt(), addStream(), addString(), clear(), copyFrom(), getItem(), loadFromStream2(), remove(), and saveToStream2().
bool BlockConfig::changed [protected]
Definition at line 22 of file BlockConfig.h.
Referenced by addBitmap(), addBoolean(), addDouble(), addInt(), addStream(), addString(), BlockConfig(), isChanged(), remove(), setBitmap(), setBoolean(), setChangedFalse(), setDouble(), setInt(), setStream(), and setString().
unsigned long BlockConfig::revision [protected]
Definition at line 23 of file BlockConfig.h.
Referenced by addBitmap(), addBoolean(), addDouble(), addInt(), addStream(), addString(), BlockConfig(), getRevision(), remove(), setBitmap(), setBoolean(), setDouble(), setInt(), setStream(), and setString().
The documentation for this class was generated from the following files:
/PIWO/Program/engine/BlockConfig.h
/PIWO/Program/engine/BlockConfig.cpp