VisualInputOutput Class Reference
#include <VisualInputOutput.h>
Public Member Functions
__fastcall VisualInputOutput (Classes::TComponent *AOwner)
Public Attributes
VisualFunction OnShowHistory
Private Member Functions
void __fastcall MouseEnterF (TObject *Sender)
void __fastcall MouseLeaveF (TObject *Sender)
void __fastcall MouseDownF (TObject *Sender, TMouseButton Button, TShiftState Shift, int X, int Y)
Detailed Description
Klasa symbolizujaca wizualnie wejscia i wyjscia do bloku
Definition at line 14 of file VisualInputOutput.h.
Constructor & Destructor Documentation
__fastcall VisualInputOutput::VisualInputOutput (Classes::TComponent * AOwner)
Konstruktor
Parameters:
AOwner wskaznik do klasy bedacej wlascicielem dla tej
Definition at line 6 of file VisualInputOutput.cpp.
References MouseDownF(), MouseEnterF(), MouseLeaveF(), and OnShowHistory.
Member Function Documentation
void __fastcall VisualInputOutput::MouseEnterF (TObject * Sender) [private]
Definition at line 25 of file VisualInputOutput.cpp.
Referenced by VisualInputOutput().
void __fastcall VisualInputOutput::MouseLeaveF (TObject * Sender) [private]
Definition at line 30 of file VisualInputOutput.cpp.
Referenced by VisualInputOutput().
void __fastcall VisualInputOutput::MouseDownF (TObject * Sender, TMouseButton Button, TShiftState Shift, int X, int Y) [private]
Definition at line 35 of file VisualInputOutput.cpp.
References OnShowHistory.
Referenced by VisualInputOutput().
Member Data Documentation
VisualFunction VisualInputOutput::OnShowHistory
Event
Definition at line 25 of file VisualInputOutput.h.
Referenced by MouseDownF(), VisualBlock::updateVisualComponents(), and VisualInputOutput().
The documentation for this class was generated from the following files:
/PIWO/Program/gui/VisualInputOutput.h
/PIWO/Program/gui/VisualInputOutput.cpp