TForm1 Class Reference
#include <main.h>
Public Member Functions
void __fastcall FormCreate (TObject *Sender)
void __fastcall Zakocz2Click (TObject *Sender)
void __fastcall Zaznaczwszystkiebloki1Click (TObject *Sender)
void __fastcall Odznaczwszystkiebloki1Click (TObject *Sender)
void __fastcall Odwrzaznaczenieblokw1Click (TObject *Sender)
void __fastcall Usubloki1Click (TObject *Sender)
void __fastcall Usuzaznaczonebloki1Click (TObject *Sender)
void __fastcall Odznaczzaznaczonepoaczenie1Click (TObject *Sender)
void __fastcall Usuwszystkiepoczenia1Click (TObject *Sender)
void __fastcall Usuzaznaczonepoczenie1Click (TObject *Sender)
void __fastcall Zresetujwszystkiepoczenia1Click (TObject *Sender)
void __fastcall Zresetujzaznaczonepoczenie1Click (TObject *Sender)
void __fastcall Uruchomwszystko1Click (TObject *Sender)
void __fastcall Uruchom3Click (TObject *Sender)
void __fastcall PageControl1Resize (TObject *Sender)
void __fastcall Wyczylogi1Click (TObject *Sender)
void __fastcall MenuItem1Click (TObject *Sender)
void __fastcall MenuItem3Click (TObject *Sender)
void __fastcall Zapiszdopliku1Zapiszjako1ClickClick (TObject *Sender)
void __fastcall MenuItem2Click (TObject *Sender)
void __fastcall MenuItem4Click (TObject *Sender)
void __fastcall PageControl1Change (TObject *Sender)
void __fastcall SpeedButton1Click (TObject *Sender)
void __fastcall Timer1Timer (TObject *Sender)
void __fastcall Nowy1Click (TObject *Sender)
void __fastcall Zakocz1Click (TObject *Sender)
void __fastcall Otwrz1Click (TObject *Sender)
void __fastcall Duplikujbloki1Click (TObject *Sender)
void __fastcall Exportujjakoobraz1Click (TObject *Sender)
void __fastcall Zapiszjako1Click (TObject *Sender)
void __fastcall FormCloseQuery (TObject *Sender, bool &CanClose)
void __fastcall Sprawdprojekt1Click (TObject *Sender)
void __fastcall Anuluj1Click (TObject *Sender)
void __fastcall ToolButton11Click (TObject *Sender)
void __fastcall ToolButton18Click (TObject *Sender)
void __fastcall ToolButton19Click (TObject *Sender)
void __fastcall ToolButton20Click (TObject *Sender)
void __fastcall ToolButton21Click (TObject *Sender)
void __fastcall ToolButton22Click (TObject *Sender)
void __fastcall FormDestroy (TObject *Sender)
void __fastcall Widok1Click (TObject *Sender)
void __fastcall Zamknijwszystkieokna1Click (TObject *Sender)
void __fastcall Pokawszystkieokna1Click (TObject *Sender)
void __fastcall Oprogramie1Click (TObject *Sender)
void __fastcall FormKeyDown (TObject *Sender, WORD &Key, TShiftState Shift)
void __fastcall ApplicationEvents1Message (tagMSG &Msg, bool &Handled)
void __fastcall Instrukcjauytkoniwka1Click (TObject *Sender)
void __fastcall Dokumentacjatechniczna1Click (TObject *Sender)
void __fastcall Oautorach1Click (TObject *Sender)
void addExt (const AnsiString &ExtMyFile)
__fastcall TForm1 (TComponent *Owner)
Public Attributes
TMainMenu * MainMenu1
TMenuItem * Plik1
TMenuItem * Edycja1
TMenuItem * Nowy1
TMenuItem * Otwrz1
TMenuItem * Zapisz1
TMenuItem * Zapiszjako1
TMenuItem * Exportujjakoobraz1
TMenuItem * Zakocz1
TMenuItem * Zaznaczwszystkiebloki1
TMenuItem * Odznaczwszystkiebloki1
TMenuItem * Odwrzaznaczenieblokw1
TMenuItem * Duplikujbloki1
TMenuItem * Usubloki1
TMenuItem * N1
TMenuItem * Zakocz2
TMenuItem * Usuzaznaczonebloki1
TMenuItem * Odznaczzaznaczonepoaczenie1
TMenuItem * Usuwszystkiepoczenia1
TMenuItem * Usuzaznaczonepoczenie1
TMenuItem * Pomoc1
TMenuItem * Instrukcjauytkoniwka1
TMenuItem * Dokumentacjatechniczna1
TMenuItem * Oautorach1
TMenuItem * Oprogramie1
TImageList * ImageList1
TStatusBar * StatusBar1
TMenuItem * Uruchom2
TMenuItem * Uruchomwszystko1
TMenuItem * Uruchom3
TMenuItem * Zresetujwszystkiepoczenia1
TMenuItem * Zresetujzaznaczonepoczenie1
TMenuItem * Widok1
TPanel * Panel1
TPageControl * PageControl1
TTabSheet * TabSheet1
TListView * ListView1
TTabSheet * TabSheet2
TTabSheet * TabSheet3
TImageList * ImageList2
TPopupMenu * PopupMenu1
TMenuItem * Wyczylogi1
TMenuItem * Zapiszdopliku1
TListView * ListView2
TListView * ListView3
TSaveDialog * SaveDialog1
TPopupMenu * PopupMenu2
TMenuItem * MenuItem1
TMenuItem * MenuItem2
TPopupMenu * PopupMenu3
TMenuItem * MenuItem3
TMenuItem * MenuItem4
TToolBar * ToolBar1
TPanel * Panel2
TCGauge * CGauge1
TLabel * Label1
TSpeedButton * SpeedButton1
TTimer * Timer1
TMenuItem * Anuluj1
TSaveDialog * SaveDialog2
TOpenDialog * OpenDialog1
TToolButton * ToolButton1
TToolButton * ToolButton2
TToolButton * ToolButton3
TToolButton * ToolButton4
TToolButton * ToolButton5
TToolButton * ToolButton6
TToolButton * ToolButton7
TToolButton * ToolButton8
TToolButton * ToolButton9
TToolButton * ToolButton10
TToolButton * ToolButton11
TToolButton * ToolButton12
TToolButton * ToolButton13
TToolButton * ToolButton14
TToolButton * ToolButton15
TToolButton * ToolButton16
TToolButton * ToolButton17
TToolButton * ToolButton18
TToolButton * ToolButton19
TToolButton * ToolButton20
TToolButton * ToolButton21
TToolButton * ToolButton22
TToolButton * ToolButton23
TToolButton * ToolButton24
TToolButton * ToolButton25
TToolButton * ToolButton26
TImageList * ImageList3
TToolButton * ToolButton27
TMenuItem * Sprawdprojekt1
TBevel * Bevel1
TMenuItem * Zamknijwszystkieokna1
TMenuItem * Pokawszystkieokna1
TMenuItem * N2
TApplicationEvents * ApplicationEvents1
PluginContener plugins
Private Member Functions
void OnLoadProgress (void *Sender, int position, int max, AnsiString info, int id)
void OnFunctionAddClick (void *Sender)
void OnLogInformation (TObject *Sender, const AnsiString message)
void OnLogDebug (TObject *Sender, const AnsiString message)
void OnLogWarrning (TObject *Sender, const AnsiString message)
void OnLogSuccess (TObject *Sender, const AnsiString message)
void OnLogError (TObject *Sender, const AnsiString message)
void OnLogRunInformation (TObject *Sender, const AnsiString message)
void OnLogRunDebug (TObject *Sender, const AnsiString message)
void OnLogRunWarrning (TObject *Sender, const AnsiString message)
void OnLogRunSuccess (TObject *Sender, const AnsiString message)
void OnLogRunError (TObject *Sender, const AnsiString message)
void OnRunStart (TObject *Sender)
void OnRunEnd (TObject *Sender)
void OnRunProgress (TObject *Sender, const AnsiString message, const double precent)
void OnChanged (TObject *Sender)
void OnBlockSelected (TObject *Sender)
void OnConnectionSelected (TObject *Sender)
void OnNothingSelected (TObject *Sender)
void __fastcall HistoryMenuClick (TObject *Sender)
void blockMenu (bool blocked)
void newProject ()
bool closeProject ()
void openProject ()
Private Attributes
PIWOEngine * piwo
AnsiString fileName
bool isBlocked
Graphics::TBitmap * defaultBlockImage
vector< FunctionDLL * > top5Added
vector< TMenuItem * > historyItems
POINT mousePos
Detailed Description
Definition at line 25 of file main.h.
Constructor & Destructor Documentation
__fastcall TForm1::TForm1 (TComponent * Owner)
Definition at line 19 of file main.cpp.
Member Function Documentation
void __fastcall TForm1::FormCreate (TObject * Sender)
Definition at line 107 of file main.cpp.
References addExt(), blockMenu(), CAPTION, PIWOEngine::defaultBlockImage, defaultBlockImage, fileName, Form2, ImageList1, PluginContener::LoadData(), PIWOEngine::loadFromFile(), TForm2::log, MainMenu1, newProject(), OnBlockSelected(), PIWOEngine::OnBlockSelected, OnChanged(), PIWOEngine::OnChanged, OnConnectionSelected(), PIWOEngine::OnConnectionSelected, PIWOEngine::OnDebug, PIWOEngine::OnError, OnFunctionAddClick(), PluginContener::OnFunctionAddRequest, PIWOEngine::OnInformation, PluginContener::OnLoadingProgress, OnLoadProgress(), OnLogDebug(), OnLogError(), OnLogInformation(), OnLogRunDebug(), OnLogRunError(), OnLogRunInformation(), OnLogRunSuccess(), OnLogRunWarrning(), OnLogSuccess(), OnLogWarrning(), OnNothingSelected(), PIWOEngine::OnNothingSelected, PIWOEngine::OnRunDebug, OnRunEnd(), PIWOEngine::OnRunEnd, PIWOEngine::OnRunError, PIWOEngine::OnRunInformation, OnRunProgress(), PIWOEngine::OnRunProgress, OnRunStart(), PIWOEngine::OnRunStart, PIWOEngine::OnRunSuccess, PIWOEngine::OnRunWarrning, PIWOEngine::OnSuccess, PIWOEngine::OnWarrning, OpenDialog1, PageControl1Change(), piwo, PIWOEngine::plugins, plugins, TForm2::ProgressBar1, and StatusBar1.
void __fastcall TForm1::Zakocz2Click (TObject * Sender)
Definition at line 400 of file main.cpp.
void __fastcall TForm1::Zaznaczwszystkiebloki1Click (TObject * Sender)
Definition at line 406 of file main.cpp.
References piwo, and PIWOEngine::SelectAllBlocks().
void __fastcall TForm1::Odznaczwszystkiebloki1Click (TObject * Sender)
Definition at line 412 of file main.cpp.
References piwo, and PIWOEngine::UnselectAllBlocks().
void __fastcall TForm1::Odwrzaznaczenieblokw1Click (TObject * Sender)
Definition at line 418 of file main.cpp.
References PIWOEngine::InvertBlockSelection(), and piwo.
void __fastcall TForm1::Usubloki1Click (TObject * Sender)
Definition at line 424 of file main.cpp.
References PIWOEngine::DeleteAllBlocks(), and piwo.
void __fastcall TForm1::Usuzaznaczonebloki1Click (TObject * Sender)
Definition at line 430 of file main.cpp.
References PIWOEngine::DeleteSelectedBlocks(), PIWOEngine::DeleteSelectedConnection(), and piwo.
void __fastcall TForm1::Odznaczzaznaczonepoaczenie1Click (TObject * Sender)
Definition at line 437 of file main.cpp.
References piwo, and PIWOEngine::UnselectSelectedConnection().
void __fastcall TForm1::Usuwszystkiepoczenia1Click (TObject * Sender)
Definition at line 443 of file main.cpp.
References PIWOEngine::DeleteAllConnections(), and piwo.
void __fastcall TForm1::Usuzaznaczonepoczenie1Click (TObject * Sender)
Definition at line 449 of file main.cpp.
References PIWOEngine::DeleteSelectedBlocks(), PIWOEngine::DeleteSelectedConnection(), and piwo.
void __fastcall TForm1::Zresetujwszystkiepoczenia1Click (TObject * Sender)
Definition at line 457 of file main.cpp.
References PIWOEngine::CancelCustomizationOnAllConnections(), and piwo.
void __fastcall TForm1::Zresetujzaznaczonepoczenie1Click (TObject * Sender)
Definition at line 463 of file main.cpp.
References PIWOEngine::CancelCustomizationOnSelectedConnections(), and piwo.
void __fastcall TForm1::Uruchomwszystko1Click (TObject * Sender)
Definition at line 469 of file main.cpp.
References blockMenu(), piwo, and PIWOEngine::run().
void __fastcall TForm1::Uruchom3Click (TObject * Sender)
Definition at line 477 of file main.cpp.
References PIWOEngine::alwaysRun, piwo, PIWOEngine::run(), ToolButton14, and Uruchom3.
void __fastcall TForm1::PageControl1Resize (TObject * Sender)
Definition at line 487 of file main.cpp.
References Label1, ListView1, ListView2, ListView3, PageControl1, TabSheet1, TabSheet2, and TabSheet3.
Referenced by OnLogDebug(), OnLogError(), OnLogInformation(), OnLogRunDebug(), OnLogRunError(), OnLogRunInformation(), OnLogRunSuccess(), OnLogRunWarrning(), OnLogSuccess(), OnLogWarrning(), and PageControl1Change().
void __fastcall TForm1::Wyczylogi1Click (TObject * Sender)
Definition at line 497 of file main.cpp.
References ListView1.
void __fastcall TForm1::MenuItem1Click (TObject * Sender)
Definition at line 503 of file main.cpp.
References ListView2.
void __fastcall TForm1::MenuItem3Click (TObject * Sender)
Definition at line 509 of file main.cpp.
References ListView3.
void __fastcall TForm1::Zapiszdopliku1Zapiszjako1ClickClick (TObject * Sender)
Definition at line 515 of file main.cpp.
References ListView1, and SaveDialog1.
void __fastcall TForm1::MenuItem2Click (TObject * Sender)
Definition at line 541 of file main.cpp.
References ListView2, and SaveDialog1.
void __fastcall TForm1::MenuItem4Click (TObject * Sender)
Definition at line 567 of file main.cpp.
References ListView3, and SaveDialog1.
void __fastcall TForm1::PageControl1Change (TObject * Sender)
Definition at line 594 of file main.cpp.
References ListView1, ListView2, ListView3, and PageControl1Resize().
Referenced by FormCreate().
void __fastcall TForm1::SpeedButton1Click (TObject * Sender)
Definition at line 629 of file main.cpp.
References PIWOEngine::abort(), and piwo.
void __fastcall TForm1::Timer1Timer (TObject * Sender)
Definition at line 638 of file main.cpp.
References Panel2, and Timer1.
void __fastcall TForm1::Nowy1Click (TObject * Sender)
Definition at line 873 of file main.cpp.
References newProject().
void __fastcall TForm1::Zakocz1Click (TObject * Sender)
Definition at line 879 of file main.cpp.
References closeProject().
void __fastcall TForm1::Otwrz1Click (TObject * Sender)
Definition at line 885 of file main.cpp.
References openProject().
void __fastcall TForm1::Duplikujbloki1Click (TObject * Sender)
Definition at line 891 of file main.cpp.
References PIWOEngine::DuplcateSelectedBlocks(), and piwo.
void __fastcall TForm1::Exportujjakoobraz1Click (TObject * Sender)
Definition at line 897 of file main.cpp.
References CAPTION, fileName, piwo, SaveDialog2, PIWOEngine::saveToFile(), and StatusBar1.
Referenced by Zapiszjako1Click().
void __fastcall TForm1::Zapiszjako1Click (TObject * Sender)
Definition at line 917 of file main.cpp.
References Exportujjakoobraz1Click(), fileName, piwo, and PIWOEngine::saveToFile().
void __fastcall TForm1::FormCloseQuery (TObject * Sender, bool & CanClose)
Definition at line 932 of file main.cpp.
References closeProject().
void __fastcall TForm1::Sprawdprojekt1Click (TObject * Sender)
Definition at line 985 of file main.cpp.
References piwo, and PIWOEngine::validateAll().
void __fastcall TForm1::Anuluj1Click (TObject * Sender)
Definition at line 991 of file main.cpp.
References PIWOEngine::abort(), and piwo.
void __fastcall TForm1::ToolButton11Click (TObject * Sender)
Definition at line 997 of file main.cpp.
References PIWOEngine::DeleteSelectedBlocks(), PIWOEngine::DeleteSelectedConnection(), and piwo.
void __fastcall TForm1::ToolButton18Click (TObject * Sender)
Definition at line 1018 of file main.cpp.
References OnFunctionAddClick(), and top5Added.
void __fastcall TForm1::ToolButton19Click (TObject * Sender)
Definition at line 1026 of file main.cpp.
References OnFunctionAddClick(), and top5Added.
void __fastcall TForm1::ToolButton20Click (TObject * Sender)
Definition at line 1034 of file main.cpp.
References OnFunctionAddClick(), and top5Added.
void __fastcall TForm1::ToolButton21Click (TObject * Sender)
Definition at line 1042 of file main.cpp.
References OnFunctionAddClick(), and top5Added.
void __fastcall TForm1::ToolButton22Click (TObject * Sender)
Definition at line 1050 of file main.cpp.
References OnFunctionAddClick(), and top5Added.
void __fastcall TForm1::FormDestroy (TObject * Sender)
Definition at line 1058 of file main.cpp.
References defaultBlockImage.
void __fastcall TForm1::Widok1Click (TObject * Sender)
Definition at line 1064 of file main.cpp.
References blockMenu(), historyItems, HistoryMenuClick(), PIWOEngine::historyWindows, isBlocked, MainMenu1, piwo, and Widok1.
void __fastcall TForm1::Zamknijwszystkieokna1Click (TObject * Sender)
Definition at line 1109 of file main.cpp.
References PIWOEngine::historyWindows, and piwo.
void __fastcall TForm1::Pokawszystkieokna1Click (TObject * Sender)
Definition at line 1120 of file main.cpp.
References PIWOEngine::historyWindows, and piwo.
void __fastcall TForm1::Oprogramie1Click (TObject * Sender)
Definition at line 1131 of file main.cpp.
References Form4.
void __fastcall TForm1::FormKeyDown (TObject * Sender, WORD & Key, TShiftState Shift)
Definition at line 1140 of file main.cpp.
References PIWOEngine::DeleteSelectedBlocks(), PIWOEngine::DeleteSelectedConnection(), and piwo.
void __fastcall TForm1::ApplicationEvents1Message (tagMSG & Msg, bool & Handled)
Definition at line 1152 of file main.cpp.
References mousePos.
void __fastcall TForm1::Instrukcjauytkoniwka1Click (TObject * Sender)
Definition at line 1164 of file main.cpp.
void __fastcall TForm1::Dokumentacjatechniczna1Click (TObject * Sender)
Definition at line 1171 of file main.cpp.
void __fastcall TForm1::Oautorach1Click (TObject * Sender)
Definition at line 1178 of file main.cpp.
References Form5.
void TForm1::OnLoadProgress (void * Sender, int position, int max, AnsiString info, int id) [private]
Definition at line 24 of file main.cpp.
References Form2, TForm2::log, OnLogSuccess(), OnLogWarrning(), and TForm2::ProgressBar1.
Referenced by FormCreate().
void TForm1::OnFunctionAddClick (void * Sender) [private]
Definition at line 47 of file main.cpp.
References PIWOEngine::AddBlock(), ImageList3, FunctionDLL::name, piwo, and top5Added.
Referenced by FormCreate(), ToolButton18Click(), ToolButton19Click(), ToolButton20Click(), ToolButton21Click(), and ToolButton22Click().
void TForm1::OnLogInformation (TObject * Sender, const AnsiString message) [private]
Definition at line 198 of file main.cpp.
References ListView1, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogDebug (TObject * Sender, const AnsiString message) [private]
Definition at line 220 of file main.cpp.
References ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogWarrning (TObject * Sender, const AnsiString message) [private]
Definition at line 255 of file main.cpp.
References ListView1, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), OnLoadProgress(), and openProject().
void TForm1::OnLogSuccess (TObject * Sender, const AnsiString message) [private]
Definition at line 233 of file main.cpp.
References ListView1, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), OnLoadProgress(), and openProject().
void TForm1::OnLogError (TObject * Sender, const AnsiString message) [private]
Definition at line 277 of file main.cpp.
References ListView1, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogRunInformation (TObject * Sender, const AnsiString message) [private]
Definition at line 299 of file main.cpp.
References ListView2, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogRunDebug (TObject * Sender, const AnsiString message) [private]
Definition at line 321 of file main.cpp.
References ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogRunWarrning (TObject * Sender, const AnsiString message) [private]
Definition at line 356 of file main.cpp.
References ListView2, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogRunSuccess (TObject * Sender, const AnsiString message) [private]
Definition at line 334 of file main.cpp.
References ListView2, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnLogRunError (TObject * Sender, const AnsiString message) [private]
Definition at line 378 of file main.cpp.
References ListView2, ListView3, and PageControl1Resize().
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnRunStart (TObject * Sender) [private]
Definition at line 605 of file main.cpp.
References blockMenu(), CGauge1, isBlocked, Label1, ListView2, and Timer1.
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnRunEnd (TObject * Sender) [private]
Definition at line 615 of file main.cpp.
References blockMenu(), isBlocked, Panel2, and Timer1.
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnRunProgress (TObject * Sender, const AnsiString message, const double precent) [private]
Definition at line 622 of file main.cpp.
References CGauge1, and Label1.
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnChanged (TObject * Sender) [private]
Definition at line 863 of file main.cpp.
References CAPTION, and fileName.
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnBlockSelected (TObject * Sender) [private]
Definition at line 1004 of file main.cpp.
References blockMenu(), and isBlocked.
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnConnectionSelected (TObject * Sender) [private]
Definition at line 1009 of file main.cpp.
References blockMenu(), and isBlocked.
Referenced by FormCreate(), newProject(), and openProject().
void TForm1::OnNothingSelected (TObject * Sender) [private]
Definition at line 1014 of file main.cpp.
References blockMenu(), and isBlocked.
Referenced by FormCreate(), newProject(), and openProject().
void __fastcall TForm1::HistoryMenuClick (TObject * Sender) [private]
Definition at line 1092 of file main.cpp.
References historyItems, PIWOEngine::historyWindows, and piwo.
Referenced by Widok1Click().
void TForm1::blockMenu (bool blocked) [private]
Definition at line 644 of file main.cpp.
References PIWOEngine::alwaysRun, Anuluj1, Duplikujbloki1, Exportujjakoobraz1, PIWOEngine::getBlockCount(), PIWOEngine::getConnectionsCount(), PIWOEngine::historyWindows, isBlocked, PIWOEngine::isBlockSelected(), PIWOEngine::isConnectionSelected(), PIWOEngine::isRuned(), Odwrzaznaczenieblokw1, Odznaczwszystkiebloki1, Odznaczzaznaczonepoaczenie1, piwo, plugins, Pokawszystkieokna1, PluginContener::setMenuItemsStatus(), Sprawdprojekt1, ToolButton10, ToolButton11, ToolButton12, ToolButton14, ToolButton15, ToolButton16, ToolButton18, ToolButton19, ToolButton20, ToolButton21, ToolButton22, ToolButton27, ToolButton3, ToolButton5, ToolButton7, ToolButton9, top5Added, Uruchom3, Uruchomwszystko1, Usubloki1, Usuwszystkiepoczenia1, Usuzaznaczonebloki1, Usuzaznaczonepoczenie1, Zakocz1, Zamknijwszystkieokna1, Zapiszjako1, Zaznaczwszystkiebloki1, Zresetujwszystkiepoczenia1, and Zresetujzaznaczonepoczenie1.
Referenced by closeProject(), FormCreate(), newProject(), OnBlockSelected(), OnConnectionSelected(), OnNothingSelected(), OnRunEnd(), OnRunStart(), openProject(), Uruchomwszystko1Click(), and Widok1Click().
void TForm1::newProject () [private]
Definition at line 750 of file main.cpp.
References blockMenu(), CAPTION, closeProject(), defaultBlockImage, PIWOEngine::defaultBlockImage, fileName, OnBlockSelected(), PIWOEngine::OnBlockSelected, OnChanged(), PIWOEngine::OnChanged, OnConnectionSelected(), PIWOEngine::OnConnectionSelected, PIWOEngine::OnDebug, PIWOEngine::OnError, PIWOEngine::OnInformation, OnLogDebug(), OnLogError(), OnLogInformation(), OnLogRunDebug(), OnLogRunError(), OnLogRunInformation(), OnLogRunSuccess(), OnLogRunWarrning(), OnLogSuccess(), OnLogWarrning(), OnNothingSelected(), PIWOEngine::OnNothingSelected, PIWOEngine::OnRunDebug, OnRunEnd(), PIWOEngine::OnRunEnd, PIWOEngine::OnRunError, PIWOEngine::OnRunInformation, OnRunProgress(), PIWOEngine::OnRunProgress, OnRunStart(), PIWOEngine::OnRunStart, PIWOEngine::OnRunSuccess, PIWOEngine::OnRunWarrning, PIWOEngine::OnSuccess, PIWOEngine::OnWarrning, piwo, plugins, PIWOEngine::plugins, and StatusBar1.
Referenced by FormCreate(), and Nowy1Click().
bool TForm1::closeProject () [private]
Definition at line 783 of file main.cpp.
References blockMenu(), CAPTION, fileName, PIWOEngine::getBlockCount(), PIWOEngine::isChanged(), piwo, SaveDialog2, PIWOEngine::saveToFile(), and StatusBar1.
Referenced by FormCloseQuery(), newProject(), openProject(), and Zakocz1Click().
void TForm1::openProject () [private]
Definition at line 815 of file main.cpp.
References blockMenu(), CAPTION, closeProject(), defaultBlockImage, PIWOEngine::defaultBlockImage, fileName, PIWOEngine::loadFromFile(), OnBlockSelected(), PIWOEngine::OnBlockSelected, OnChanged(), PIWOEngine::OnChanged, OnConnectionSelected(), PIWOEngine::OnConnectionSelected, PIWOEngine::OnDebug, PIWOEngine::OnError, PIWOEngine::OnInformation, OnLogDebug(), OnLogError(), OnLogInformation(), OnLogRunDebug(), OnLogRunError(), OnLogRunInformation(), OnLogRunSuccess(), OnLogRunWarrning(), OnLogSuccess(), OnLogWarrning(), OnNothingSelected(), PIWOEngine::OnNothingSelected, PIWOEngine::OnRunDebug, OnRunEnd(), PIWOEngine::OnRunEnd, PIWOEngine::OnRunError, PIWOEngine::OnRunInformation, OnRunProgress(), PIWOEngine::OnRunProgress, OnRunStart(), PIWOEngine::OnRunStart, PIWOEngine::OnRunSuccess, PIWOEngine::OnRunWarrning, PIWOEngine::OnSuccess, PIWOEngine::OnWarrning, OpenDialog1, piwo, plugins, PIWOEngine::plugins, and StatusBar1.
Referenced by Otwrz1Click().
void TForm1::addExt (const AnsiString & ExtMyFile)
Definition at line 938 of file main.cpp.
Referenced by FormCreate().
Member Data Documentation
TMainMenu* TForm1::MainMenu1
Definition at line 28 of file main.h.
Referenced by FormCreate(), and Widok1Click().
TMenuItem* TForm1::Plik1
Definition at line 29 of file main.h.
TMenuItem* TForm1::Edycja1
Definition at line 30 of file main.h.
TMenuItem* TForm1::Nowy1
Definition at line 31 of file main.h.
TMenuItem* TForm1::Otwrz1
Definition at line 32 of file main.h.
TMenuItem* TForm1::Zapisz1
Definition at line 33 of file main.h.
TMenuItem* TForm1::Zapiszjako1
Definition at line 34 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Exportujjakoobraz1
Definition at line 35 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Zakocz1
Definition at line 36 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Zaznaczwszystkiebloki1
Definition at line 37 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Odznaczwszystkiebloki1
Definition at line 38 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Odwrzaznaczenieblokw1
Definition at line 39 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Duplikujbloki1
Definition at line 40 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Usubloki1
Definition at line 41 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::N1
Definition at line 42 of file main.h.
TMenuItem* TForm1::Zakocz2
Definition at line 43 of file main.h.
TMenuItem* TForm1::Usuzaznaczonebloki1
Definition at line 44 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Odznaczzaznaczonepoaczenie1
Definition at line 45 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Usuwszystkiepoczenia1
Definition at line 46 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Usuzaznaczonepoczenie1
Definition at line 47 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Pomoc1
Definition at line 48 of file main.h.
TMenuItem* TForm1::Instrukcjauytkoniwka1
Definition at line 49 of file main.h.
TMenuItem* TForm1::Dokumentacjatechniczna1
Definition at line 50 of file main.h.
TMenuItem* TForm1::Oautorach1
Definition at line 51 of file main.h.
TMenuItem* TForm1::Oprogramie1
Definition at line 52 of file main.h.
TImageList* TForm1::ImageList1
Definition at line 53 of file main.h.
Referenced by FormCreate().
TStatusBar* TForm1::StatusBar1
Definition at line 54 of file main.h.
Referenced by closeProject(), Exportujjakoobraz1Click(), FormCreate(), newProject(), and openProject().
TMenuItem* TForm1::Uruchom2
Definition at line 55 of file main.h.
TMenuItem* TForm1::Uruchomwszystko1
Definition at line 56 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Uruchom3
Definition at line 57 of file main.h.
Referenced by blockMenu(), and Uruchom3Click().
TMenuItem* TForm1::Zresetujwszystkiepoczenia1
Definition at line 58 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Zresetujzaznaczonepoczenie1
Definition at line 59 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Widok1
Definition at line 60 of file main.h.
Referenced by Widok1Click().
TPanel* TForm1::Panel1
Definition at line 61 of file main.h.
TPageControl* TForm1::PageControl1
Definition at line 62 of file main.h.
Referenced by PageControl1Resize().
TTabSheet* TForm1::TabSheet1
Definition at line 63 of file main.h.
Referenced by PageControl1Resize().
TListView* TForm1::ListView1
Definition at line 64 of file main.h.
Referenced by OnLogError(), OnLogInformation(), OnLogSuccess(), OnLogWarrning(), PageControl1Change(), PageControl1Resize(), Wyczylogi1Click(), and Zapiszdopliku1Zapiszjako1ClickClick().
TTabSheet* TForm1::TabSheet2
Definition at line 65 of file main.h.
Referenced by PageControl1Resize().
TTabSheet* TForm1::TabSheet3
Definition at line 66 of file main.h.
Referenced by PageControl1Resize().
TImageList* TForm1::ImageList2
Definition at line 67 of file main.h.
TPopupMenu* TForm1::PopupMenu1
Definition at line 68 of file main.h.
TMenuItem* TForm1::Wyczylogi1
Definition at line 69 of file main.h.
TMenuItem* TForm1::Zapiszdopliku1
Definition at line 70 of file main.h.
TListView* TForm1::ListView2
Definition at line 71 of file main.h.
Referenced by MenuItem1Click(), MenuItem2Click(), OnLogRunError(), OnLogRunInformation(), OnLogRunSuccess(), OnLogRunWarrning(), OnRunStart(), PageControl1Change(), and PageControl1Resize().
TListView* TForm1::ListView3
Definition at line 72 of file main.h.
Referenced by MenuItem3Click(), MenuItem4Click(), OnLogDebug(), OnLogError(), OnLogInformation(), OnLogRunDebug(), OnLogRunError(), OnLogRunInformation(), OnLogRunSuccess(), OnLogRunWarrning(), OnLogSuccess(), OnLogWarrning(), PageControl1Change(), and PageControl1Resize().
TSaveDialog* TForm1::SaveDialog1
Definition at line 73 of file main.h.
Referenced by MenuItem2Click(), MenuItem4Click(), and Zapiszdopliku1Zapiszjako1ClickClick().
TPopupMenu* TForm1::PopupMenu2
Definition at line 74 of file main.h.
TMenuItem* TForm1::MenuItem1
Definition at line 75 of file main.h.
TMenuItem* TForm1::MenuItem2
Definition at line 76 of file main.h.
TPopupMenu* TForm1::PopupMenu3
Definition at line 77 of file main.h.
TMenuItem* TForm1::MenuItem3
Definition at line 78 of file main.h.
TMenuItem* TForm1::MenuItem4
Definition at line 79 of file main.h.
TToolBar* TForm1::ToolBar1
Definition at line 80 of file main.h.
TPanel* TForm1::Panel2
Definition at line 81 of file main.h.
Referenced by OnRunEnd(), and Timer1Timer().
TCGauge* TForm1::CGauge1
Definition at line 82 of file main.h.
Referenced by OnRunProgress(), and OnRunStart().
TLabel* TForm1::Label1
Definition at line 83 of file main.h.
Referenced by OnRunProgress(), OnRunStart(), and PageControl1Resize().
TSpeedButton* TForm1::SpeedButton1
Definition at line 84 of file main.h.
TTimer* TForm1::Timer1
Definition at line 85 of file main.h.
Referenced by OnRunEnd(), OnRunStart(), and Timer1Timer().
TMenuItem* TForm1::Anuluj1
Definition at line 86 of file main.h.
Referenced by blockMenu().
TSaveDialog* TForm1::SaveDialog2
Definition at line 87 of file main.h.
Referenced by closeProject(), and Exportujjakoobraz1Click().
TOpenDialog* TForm1::OpenDialog1
Definition at line 88 of file main.h.
Referenced by FormCreate(), and openProject().
TToolButton* TForm1::ToolButton1
Definition at line 89 of file main.h.
TToolButton* TForm1::ToolButton2
Definition at line 90 of file main.h.
TToolButton* TForm1::ToolButton3
Definition at line 91 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton4
Definition at line 92 of file main.h.
TToolButton* TForm1::ToolButton5
Definition at line 93 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton6
Definition at line 94 of file main.h.
TToolButton* TForm1::ToolButton7
Definition at line 95 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton8
Definition at line 96 of file main.h.
TToolButton* TForm1::ToolButton9
Definition at line 97 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton10
Definition at line 98 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton11
Definition at line 99 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton12
Definition at line 100 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton13
Definition at line 101 of file main.h.
TToolButton* TForm1::ToolButton14
Definition at line 102 of file main.h.
Referenced by blockMenu(), and Uruchom3Click().
TToolButton* TForm1::ToolButton15
Definition at line 103 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton16
Definition at line 104 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton17
Definition at line 105 of file main.h.
TToolButton* TForm1::ToolButton18
Definition at line 106 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton19
Definition at line 107 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton20
Definition at line 108 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton21
Definition at line 109 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton22
Definition at line 110 of file main.h.
Referenced by blockMenu().
TToolButton* TForm1::ToolButton23
Definition at line 111 of file main.h.
TToolButton* TForm1::ToolButton24
Definition at line 112 of file main.h.
TToolButton* TForm1::ToolButton25
Definition at line 113 of file main.h.
TToolButton* TForm1::ToolButton26
Definition at line 114 of file main.h.
TImageList* TForm1::ImageList3
Definition at line 115 of file main.h.
Referenced by OnFunctionAddClick().
TToolButton* TForm1::ToolButton27
Definition at line 116 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Sprawdprojekt1
Definition at line 117 of file main.h.
Referenced by blockMenu().
TBevel* TForm1::Bevel1
Definition at line 118 of file main.h.
TMenuItem* TForm1::Zamknijwszystkieokna1
Definition at line 119 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::Pokawszystkieokna1
Definition at line 120 of file main.h.
Referenced by blockMenu().
TMenuItem* TForm1::N2
Definition at line 121 of file main.h.
TApplicationEvents* TForm1::ApplicationEvents1
Definition at line 122 of file main.h.
PIWOEngine* TForm1::piwo [private]
Definition at line 174 of file main.h.
Referenced by Anuluj1Click(), blockMenu(), closeProject(), Duplikujbloki1Click(), Exportujjakoobraz1Click(), FormCreate(), FormKeyDown(), HistoryMenuClick(), newProject(), Odwrzaznaczenieblokw1Click(), Odznaczwszystkiebloki1Click(), Odznaczzaznaczonepoaczenie1Click(), OnFunctionAddClick(), openProject(), Pokawszystkieokna1Click(), SpeedButton1Click(), Sprawdprojekt1Click(), ToolButton11Click(), Uruchom3Click(), Uruchomwszystko1Click(), Usubloki1Click(), Usuwszystkiepoczenia1Click(), Usuzaznaczonebloki1Click(), Usuzaznaczonepoczenie1Click(), Widok1Click(), Zamknijwszystkieokna1Click(), Zapiszjako1Click(), Zaznaczwszystkiebloki1Click(), Zresetujwszystkiepoczenia1Click(), and Zresetujzaznaczonepoczenie1Click().
AnsiString TForm1::fileName [private]
Definition at line 175 of file main.h.
Referenced by closeProject(), Exportujjakoobraz1Click(), FormCreate(), newProject(), OnChanged(), openProject(), and Zapiszjako1Click().
bool TForm1::isBlocked [private]
Definition at line 176 of file main.h.
Referenced by blockMenu(), OnBlockSelected(), OnConnectionSelected(), OnNothingSelected(), OnRunEnd(), OnRunStart(), and Widok1Click().
Graphics::TBitmap* TForm1::defaultBlockImage [private]
Definition at line 177 of file main.h.
Referenced by FormCreate(), FormDestroy(), newProject(), and openProject().
vector<FunctionDLL*> TForm1::top5Added [private]
Definition at line 178 of file main.h.
Referenced by blockMenu(), OnFunctionAddClick(), ToolButton18Click(), ToolButton19Click(), ToolButton20Click(), ToolButton21Click(), and ToolButton22Click().
vector<TMenuItem*> TForm1::historyItems [private]
Definition at line 179 of file main.h.
Referenced by HistoryMenuClick(), and Widok1Click().
POINT TForm1::mousePos [private]
Definition at line 180 of file main.h.
Referenced by ApplicationEvents1Message().
PluginContener TForm1::plugins
Definition at line 212 of file main.h.
Referenced by blockMenu(), FormCreate(), newProject(), and openProject().
The documentation for this class was generated from the following files:
/PIWO/Program/main.h
/PIWO/Program/main.cpp